In [5]:
import pandas as pd
df = pd.read_csv("../data.csv")
df.set_index('id', inplace=True)
df.head()

,url,path,project_names
id,,,
0,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c1544.html,['Westgold Resources Limited (ASX: WGX)']
1,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c5893.html,"['Berens Bridge & Road Project', 'PAK Lithium ..."
2,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c4520.html,"['Columba High Grade Silver Project', 'Kootena..."
3,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c4355.html,"['Big Bear Copper Property', 'Black Mammoth Me..."
4,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c1563.html,"['El Quevar', 'Mani-Copan', 'Carmen']"

In [9]:
df.drop_duplicates(subset=['path'], inplace=True)
df.dropna(subset=['project_names'], inplace=True)

In [10]:
df.describe()

,url,path,project_names
count,5588,5588,5588
unique,5588,5588,4814
top,http://www.newswire.ca/en/releases/archive/Feb...,articles/February202623c1544.html,"['Lunahuasi', 'Los Helados']"
freq,1,1,26

In [ ]:
for idx, row in df.iterrows():
    try:
        tables = pd.read_html("../" + row.get('path'))
    except:
        tables = []
    for table in tables:
        is_resource = is_resource_table(table)
        if is_resource:
            print(is_resource, table.head(), sep='\t')
            input()

True	                           0                                 1  \
0  Mineral Resource Estimate         Mineral Resource Estimate
1                     Domain  Tonnes Above Cut- off (millions)
2                   Measured                            858.26
3                  Indicated                            280.33
4       Measured & Indicated                           1138.59

                           2                          3  \
0  Mineral Resource Estimate  Mineral Resource Estimate
1             Li Grade (ppm)   Li Contained (million t)
2                        990                      0.850
3                        891                      0.250
4                        966                      1.099

                           4
0  Mineral Resource Estimate
1            LCE (million t)
2                      4.523
3                      1.329
4                      5.852

True	                          0                                1  \
0  Mineral Reserve Estimate         Mineral Reserve Estimate
1                    Domain  Tonnes Above Cut-off (millions)
2                    Proven                           266.39
3                  Probable                            21.26
4         Proven & Probable                           287.65

                          2                         3  \
0  Mineral Reserve Estimate  Mineral Reserve Estimate
1            Li Grade (ppm)   Li Contained(million t)
2                      1147                     0.306
3                      1174                     0.025
4                      1149                     0.330

                          4
0  Mineral Reserve Estimate
1           LCE (million t)
2                     1.626
3                     0.133
4                     1.759

In [52]:
from io import StringIO
tables = pd.read_html(StringIO(text))
for table in tables:
    is_resource = is_resource_table(table)
    print(is_resource)

True

In [45]:
text = """
<html lang="en"><head>
  
        <meta charset="utf-8">
	    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
	    <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/content/dam/cision/icons/favicon.png" type="image/png">
    	<meta name="adobeLaunchScript" content="//assets.adobedtm.com/launch-EN5a9546be82474822b2c7515efd01750c.min">
		<script type="text/javascript" src="https://widgets.financialcontent.com/cision/stockquote.js" async=""></script>
	
 



<script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>
<script src="https://fast.wistia.com/player.js" async=""></script>
<script src="https://fast.wistia.com/playlist.js" async=""></script> 
    
<link rel="stylesheet" href="/etc.clientlibs/prncom/clientlibs/newspage-clientlibs.min.css" type="text/css">





     
    
     
    <meta itemprop="description" content="/CNW/ - Star Diamond Corporation (&quot;Star Diamond&quot; or the &quot;Company&quot;) is pleased to announce a significant increase in the estimated Mineral Resources for the...">
    <meta name="description" content="/CNW/ - Star Diamond Corporation (&quot;Star Diamond&quot; or the &quot;Company&quot;) is pleased to announce a significant increase in the estimated Mineral Resources for the...">
    <!-- For structured data -->
    <meta itemprop="inLanguage" content="en">
    <!-- For language declaration -->
    <meta http-equiv="Content-Language" content="en">
    
    
        <link rel="icon" href="/content/dam/cision/icons/favicon.png" type="image/png">
    
    <title>STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE</title>
    <meta name="author" content="Star Diamond Corporation">
    <meta name="Publisher" content="CNW Group">
    <meta name="msvalidate.01" content="9D28F7743C790DD88F2D9C7375EF7ED5">
    <meta name="p:domain_verify" content="7d052ac42aa9e7505635404745861994">
    <meta name="referrer" content="unsafe-url">
    <meta name="google-site-verification" content="xDAXH-iSoJ2LVjsJb88HI03rnWfjQ3sQcczI4-EGotQ">
    <meta name="naver-site-verification" content="0aaad19c909a94c1b1cf1e782a10f0a6d8e14fc0">
    <meta name="date" content="2024-07-24T11:06:00-04:00">
    <meta name="twitter:card" content="summary_large_image">
    
        <meta name="twitter:site" content="@CNWGroup">
    
    
    <meta name="twitter:title" content="STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE">
    <meta name="twitter:description" content="/CNW/ - Star Diamond Corporation (&quot;Star Diamond&quot; or the &quot;Company&quot;) is pleased to announce a significant increase in the estimated Mineral Resources for the...">
    
        <meta name="twitter:image" content="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?p=twitter">
    
    <meta property="og:title" content="STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE">
    <meta property="og:type" content="article">
    <meta property="og:description" content="/CNW/ - Star Diamond Corporation (&quot;Star Diamond&quot; or the &quot;Company&quot;) is pleased to announce a significant increase in the estimated Mineral Resources for the...">
    
        
            
                <meta property="og:image" content="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?p=facebook">
            
        
    
    
     
    <meta property="og:url" content="https://www.newswire.ca/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html">
    
        
        

            
            
                
                    
                        <meta name="robots" content="index, follow, max-image-preview:large">
                    
                    
                    
                
                
                <link rel="canonical" href="https://www.newswire.ca/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html">
                
            
        

    
    <meta id="sharingTitle" content="STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE">
    <meta id="sharingDesc" content="STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE">
     
    
    
    <!-- Additional Authorable Meta tags -->
    
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "NewsArticle",
            "mainEntityOfPage": {
                "@id": "https://www.newswire.ca/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html"
            },
            "headline": "STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE",
            "image": [
                "https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT REVI.jpg?p=facebook"
            ],
            "datePublished": "2024-07-24T11:06:00-04:00",
            "dateModified": "2024-07-24T11:06:00-04:00",
            "description": "/CNW/ - Star Diamond Corporation (&quot;Star Diamond&quot; or the &quot;Company&quot;) is pleased to announce a significant increase in the estimated Mineral Resources for the...",
            "publisher": {
              "@type": "Organization",
              "name": "CNW Group",
              "logo": {
                "@type": "ImageObject",
                "url": "https://www.newswire.ca/content/dam/newswire-ca/Cision_logo_navy_orange.svg"
              }
            }
        }
    </script>
 
			 	<style>
			 		
/* Style Definitions */
span.prnews_span
{
font-size:8pt;
font-family:"Arial";
color:black;
}
a.prnews_a
{
color:blue;
}
li.prnews_li
{
font-size:8pt;
font-family:"Arial";
color:black;
}
p.prnews_p
{
font-size:0.62em;
font-family:"Arial";
color:black;
margin:0in;
}
.prngen13{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; TEXT-ALIGN: CENTER; BORDER-TOP:black 1pt; BORDER-RIGHT:black 1pt; BORDER-BOTTOM:black 1pt; BORDER-LEFT:black 1pt
}
.prngen12{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; TEXT-ALIGN: RIGHT; BORDER-TOP:black 1pt; BORDER-RIGHT:black 1pt; BORDER-BOTTOM:black 1pt; BORDER-LEFT:black 1pt
}
.prngen3{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; TEXT-ALIGN: RIGHT; BORDER-TOP:black 1pt; BORDER-RIGHT:black 0.5pt solid; BORDER-BOTTOM:black 1pt; BORDER-LEFT:black 1pt
}
.prngen6{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; TEXT-ALIGN: CENTER; BORDER-TOP:black 1pt; BORDER-RIGHT:black 0.5pt solid; BORDER-BOTTOM:black 0.5pt solid; BORDER-LEFT:black 1pt
}
.prngen10{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; TEXT-ALIGN: RIGHT; BORDER-TOP:black 1pt; BORDER-RIGHT:black 0.5pt solid; BORDER-BOTTOM:black 0.5pt solid; BORDER-LEFT:black 1pt
}
.prngen8{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; TEXT-ALIGN: CENTER; BORDER-TOP:black 0.5pt solid; BORDER-RIGHT:black 0.5pt solid; BORDER-BOTTOM:black 0.5pt solid; BORDER-LEFT:black 1pt
}
.prngen11{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; BORDER-TOP:black 1pt; BORDER-RIGHT:black 0.5pt solid; BORDER-BOTTOM:black 0.5pt solid; BORDER-LEFT:black 1pt
}
.prngen9{
PADDING-RIGHT:0.17em; PADDING-LEFT:0.17em; VERTICAL-ALIGN: BOTTOM; BORDER-TOP:black 1pt; BORDER-RIGHT:black 0.5pt solid; BORDER-BOTTOM:black 0.5pt solid; BORDER-LEFT:black 0.5pt solid
}
.prnsblb1{
BORDER-LEFT:black 1pt
}
.prnml4{
MARGIN-TOP:0em; MARGIN-RIGHT:0em; MARGIN-BOTTOM:0em; MARGIN-LEFT:0.33em !IMPORTANT
}
.prnsbbb1{
BORDER-BOTTOM:black 1pt
}
.prnpl2{
PADDING-LEFT:0.17em
}
.prntac{
TEXT-ALIGN: CENTER
}
.prnbbbs{
BORDER-BOTTOM:black 0.5pt solid
}
.prnbrbrs{
BORDER-RIGHT:black 0.5pt solid
}
.prnsbtb1{
BORDER-TOP:black 1pt
}
.prncbts{
BORDER-TOP:black 0.5pt solid
}
.prnpr2{
PADDING-RIGHT:0.17em
}
.prnbcc{
BORDER-COLLAPSE: COLLAPSE; BORDER-TOP:1pt  black; BORDER-RIGHT:1pt  black; BORDER-BOTTOM:1pt  black; BORDER-LEFT:1pt  black
}
.prntal{
TEXT-ALIGN: LEFT
}
.prnvab{
VERTICAL-ALIGN: BOTTOM
}
.prnbsbls{
BORDER-LEFT:black 0.5pt solid
}

			 	</style>
		 	          

	

<script src="https://browser.sentry-cdn.com/9.6.1/bundle.min.js" crossorigin="anonymous" integrity="sha384-kbRmCeIl7Uxr+vT9YhSAdguCdd4L5QPRj7jzQTanorUVVlw/Y5X9vtzVyOEHLfpH"></script><style>.glyph-loading {
  display: flex;
  width: 100%;
  flex: 1;
  font-size: 7rem;
  align-items: center;
  justify-content: center;
}
.glyph-loading svg {
  display: inline-block;
  height: 1em;
  line-height: 1;
}
.stockquote {
  width: 600px;
  font-family: Montserrat, sans-serif;
  font-size: 12px;
}
.stockquote h2.stockname {
  font-size: 16px;
  font-weight: bold;
  margin: 5px 0px;
}
.stockquote .timestamp {
  font-size: 12px;
  font-weight: normal;
  padding: 0px 0px 8px 0px;
}
.stockquote .data-left {
  float: left;
  width: 280px;
}
.stockquote .data-right {
  float: right;
}
.stockquote .clearfix::after {
  content: "";
  clear: both;
  display: table;
}
.stockquote .datatable {
  display: table;
  width: 100%;
}
.stockquote .row {
  display: table-row;
}
.stockquote .left-col {
  display: table-cell;
  padding: 8px 0px;
}
.stockquote .right-col {
  text-align: right;
  display: table-cell;
  padding: 8px 0px;
}
.stockquote .positive {
  color: #5CAC00;
}
.stockquote .negative {
  color: #990000;
}
.stockquote .intervalTable {
  display: table;
  width: 100%;
}
.stockquote .chart {
  padding-top: 6px;
}
.stockquote button {
  font-family: Montserrat, sans-serif;
  font-size: 12px;
  color: #272729;
  padding: 4px 8px !important;
  font-weight: bold;
  margin-left: 3px;
  margin-right: 3px;
  background-color: #FFF;
  border-radius: 8px;
  border: 2px solid #FFF;
}
.stockquote button[aria-selected='true'] {
  background-color: #00837E;
  color: #FFF;
  border: 2px solid #00837E;
}
</style></head>


<body class="prncom prncom_news-releases prncom_news-releases_news-template-b prncom_news-releases_news-template-b_index inline-gallery-template news blue-theme">
<a href="https://www.cision.com/about/accessibility/" tabindex="0" class="skipNavLink screen-only">Accessibility Statement</a>
<a href="#main" tabindex="0" class="skipNavLink screen-only">Skip Navigation</a>
<div class="page-wrap">
  

<div>
			 

    <header class="main-header visible-lg-block newswire-ca ">
    

 
<section class="nav-junior">
    <div class="container">
        <nav class="navbar navbar-junior" aria-label="primary">
                <div>
                    
                        
                        <ul class="nav navbar-nav"> 
                                <li>
                                <a href="/resources/" target="_self">Resources</a>
                              </li> 
                                <li>
                                <a href="/products/investor-relations/" target="_self">Investor Relations</a>
                              </li> <li>
                           <a href="https://prnmedia.prnewswire.com/" target="_blank">Journalists</a>
                             </li>
                                 <li>
                           <a href="https://cnw.en.mediaroom.com/events" target="_blank">Webcasts</a>
                             </li>
                                  </ul>
                    
                    
                        
                      <ul class="nav navbar-nav navbar-right">  <li>
											<!-- <a href="JavaScript:void(0)"  id="userlang" target="_self" class="language-toggle" data-browser-lang="en" data-req-param-org="" data-req-url="/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html" data-req-full-url="https://www.newswire.ca/content/newswire-ca/ca/en/news-releases.detail.html/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html"  data-redirect-url="/fr/news-releases/" title="" style="cursor:pointer;">Français</a> -->
											<a href="/fr/news-releases/" class="language-toggle" target="_self" lang="fr">Français</a>
                                       </li><li class="dropdown ">
                                                    <a tabindex="0" data-toggle="dropdown" role="button" class="dropdown-toggle" aria-expanded="false">my CNW&nbsp; <i class="btr bt-angle-down"></i></a>
                                                    <ul class="dropdown-menu"> 
            <li>
                <a href="/mycnw/login/" id="logRegister" target="_self">Login</a>
            </li>  
            <li>
                <a href="/mycnw/register/" id="regRegister" target="_self">Register</a>
            </li> 
                                                    </ul>
                                                </li><li class="dropdown ">
                                                    <a tabindex="0" data-toggle="dropdown" role="button" class="dropdown-toggle" aria-expanded="false">Client Login&nbsp; <i class="btr bt-angle-down"></i></a>
                                                    <ul class="dropdown-menu"> <li>
                <a href="https://app.prnewswire.com/login/auto" target="_blank">PR Newswire Amplify™</a>
            </li>
              <li>
                <a href="https://app2.cision.com/" target="_blank">Next Gen Communications Cloud</a>
            </li>
              <li>
                <a href="https://app.cision.com/#/login?lang=en-ca" target="_blank">Cision Communications Cloud®</a>
            </li>
             
                                                    </ul>
                                                </li><li>
                                           <a href="/contact-us/" target="_blank">Sign Up</a>
                                     </li>   <li class="bg-brand-secondary ">
                                    <a href="/contact-us/" target="_self">Send a Release</a>
                                </li>
                                 </ul>
                    
                </div>
        </nav>
    </div>
</section>
    <section class="nav-main">
    <div class="container">
        <nav class="navbar navbar-default" aria-label="secondary">
                <div class="navbar-header">
                    


<a class="navbar-brand" href="/home/" target="_self">
        
        
            
            <img class="img-responsive " src="" title="Return to PR Newswire homepage" alt="Return to PR Newswire homepage" loading="lazy" onerror="this.onerror=null; this.src=''">
            
            
        
    </a>
               </div>
               <div>
                    



	<ul class="nav navbar-nav">
		
			<li class="dropdown" id="news">
				
				
					<a href="/news-releases/" target="_self" data-subnav="news">News</a>
				
			</li>
		
			<li class="dropdown" id="products">
				
				
					<a href="/amplify-platform/" target="_self" data-subnav="products">Products</a>
				
			</li>
		
			<li class="dropdown" id="contact">
				
				
					<a href="/contact-us/" target="_self" data-subnav="contact">Contact</a>
				
			</li>
		
	</ul>

                </div>
				
                    <div>
					 
					   
					  		


	
	
			
		<script>
			var siteSearchProperties = '{"viewAllorglabelHtml":"Organizations <span>View all</span>","viewAllprodlabelHtml":null,"viewAllresourcelabelHtml":null,"newsReleasePrefix":null,"viewAllNewslabelHtml":"News <span>View all</span>"}';
			siteSearchProperties = JSON.parse(siteSearchProperties);
		</script>
	   		<div id="sitesearch">
	   		

	 <div class="pull-right">
          <button data-toggle="modal" data-target="#search-modal" class="search_btn">
              Search<span aria-hidden="true" class="btr bt-search bt-lg text-muted"></span>
             
             
            <input type="hidden" id="pathPrefix" name="pathPrefix">
            <input type="hidden" id="siteValue" name="siteValue" value="newswire-ca">
            <input type="hidden" id="langValue" name="langValue" value="en">
        </button>
     </div>
 
 
 
 
 
 

<div class="modal fade modal-qs-search" id="search-modal" tabindex="-1">
          <div role="dialog" aria-modal="true" aria-label="Search" class="modal-dialog modal-lg">
            <div class="modal-content">
            <div class="col-sm-1 pull-right">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="btr bt-times"></i></button>
            </div>
              <div class="modal-body col-sm-10 col-sm-offset-1" tabindex="0">
                <form class="search-bar">
                  <div class="input-group">

                  	<input type="hidden" id="sitesearchurl" name="searchlink" value="/search/all/">
                  	<input type="hidden" id="prodsearchurl" name="prodsearchlink" value="/search/products/">
                  	<input type="hidden" id="resourcesearchurl" name="resourcesearchlink" value="/search/all/">
                  	<input type="hidden" id="orgsearchurl" name="orgsearchlink" value="/search/organization/">
                  	<input type="hidden" id="allnewssearchurl" name="allnewssearchlink" value="/search/news/">
                  	<input type="hidden" id="enableQuickSearch" name="enableQuickSearch" value="true">

                  	<input type="hidden" id="newsVanityPathURL" name="newsVanityPathURL" value="/news/">
                      <input type="hidden" id="currentPagePathURL" name="currentPagePathURL" value="/content/newswire-ca/ca/en/news-releases">
                      <label class="search-label" id="SearchLabel" for="sitesearchbox">Search</label>
                  	 <span style="display: none" id="autopoplabel" aria-hidden="true">When typing in this field, a list of search results will appear and be automatically updated as you type.</span>
                      <div class="results-count sr-only" aria-live="assertive"></div>
                      <input type="text" id="sitesearchbox" name="Search" aria-controls="results" aria-haspopup="listbox" aria-expanded="false" aria-describedby="autopoplabel" autocomplete="off" aria-autocomplete="list" class="form-control form-search" placeholder="Search News Releases, Organizations">

                  </div>
                  <div class="qs-error">
                  </div>
                </form>
              <div class="qs-results-container">
                  <div class="qs-pending">
                    <div class="row">
                      <div class="col-sm-1">
                        <div class="uil-ring-css small">
                          <div></div>
                        </div>
                      </div>
                      <div class="col-sm-11">
                        <p class="text-muted">Searching for your content...</p>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="qs-results" id="response-json">
                        <div class="media qs-no-results">
		                  <div class="media-left media-middle">
		                    <i class="btr bt-exclamation-circle bt-2x text-muted"></i>
		                  </div>
		                  <div class="media-body media-middle">
		                    <span><strong>No results found. Please change your search terms and try again.</strong></span>
		                  </div>
		                </div>

                        <div id="eraResponseJson"> </div>
                      </div>
                      
	                      <div class="row">
	                        <div class="col-sm-12">
	                          <a class="qs-as" href="/search/advance-search/">Advanced Search</a>
	                        </div>
	                      </div>
                      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
	
	   		</div>
		

		

					   
					  	                   
					
					</div>
				
           </nav>
           
    </div>
</section>

    
                <div class="navigation-menu" id="sub-nav-tier" style="display: none;">
                    <div class="nav-subnav hidden-xs">
						<div class="container">
							
								
									<nav class="navbar news" id="mainNav-news" style="display: none;" aria-label="news">
										
											
											

  <ul class="nav nav-pills tier-two  advsearch">
    
      
        
          
          
          
            <li class="nav-dropdown dropdown fw nav-title">
              <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" tabindex="0" aria-expanded="false" aria-controls="1-submenu" title="News in Focus"> News in Focus </a>
              
                
                  
                  <ul class="dropdown-menu tier-three" id="1-submenu">
                    <li class="row">
                      <div class="col-sm-12">
                        <div class="nav-list-item">
                          
	
	
	
	
		
		
			
				<div class="col-sm-4">
					<ul class="nav-tier col_item col_item_list2">
						<li><h2><a href="/news-releases/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | News in Focus | Browse News Releases&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}" class="media-heading omniture-subnav" style="font-weight:bold">Browse News Releases</a></h2></li>
						
							
							
	
		<li>
			<a class="omniture-subnav" href="/news-releases/news-releases-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All News Releases
			</a>
		</li>
	
		<li>
			<a class="omniture-subnav" href="/news-releases/all-public-company-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Public Company
			</a>
		</li>
	

						


						
							
							
						
						
							
								<li><h2><a class="media-heading omniture-subnav" href="/news-releases/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | News in Focus | Browse News Releases | Browse News Releases Overview&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">News Releases Overview </a></h2></li>
							

						
						
					</ul>
				</div>
			
		
			
				<div class="col-sm-4">
					<ul class="nav-tier col_item col_item_list2">
						<li><h2><a href="/news-releases/multimedia/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | News in Focus | Multimedia Gallery&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}" class="media-heading omniture-subnav" style="font-weight:bold">Multimedia Gallery</a></h2></li>
						
							
							
	
		<li>
			<a class="omniture-subnav" href="/news-releases/multimedia/multimedia-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Multimedia
			</a>
		</li>
	
		<li>
			<a class="omniture-subnav" href="/news-releases/photos/photos-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Photos
			</a>
		</li>
	
		<li>
			<a class="omniture-subnav" href="/news-releases/videos/videos-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Videos
			</a>
		</li>
	

						


						
							
							
						
						
							
								<li><h2><a class="media-heading omniture-subnav" href="/news-releases/multimedia/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | News in Focus | Multimedia Gallery | Multimedia Gallery Overview&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Multimedia Gallery Overview </a></h2></li>
							

						
						
					</ul>
				</div>
			
		
			
				<div class="col-sm-4">
					<ul class="nav-tier col_item col_item_list2">
						<li><h2><a href="/news-releases/latest-news-topics/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | News in Focus | Trending Topics&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}" class="media-heading omniture-subnav" style="font-weight:bold">Trending Topics</a></h2></li>
						
							
							
	
		<li>
			<a class="omniture-subnav" href="/news-releases/latest-news-topics/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Trending Topics
			</a>
		</li>
	

						


						
						
							

						
						
					</ul>
				</div>
			
		
	


                        </div>
                      </div>
                    </li>
                  </ul>
                
              
              
            </li>
          
        
          
          
          
            <li class="nav-dropdown dropdown fw nav-title">
              <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" tabindex="0" aria-expanded="false" aria-controls="2-submenu" title="Business"> Business </a>
              
              
                
                  
                  <ul class="dropdown-menu tier-three">
    <li class="row">
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/automotive-transportation-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Business&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Auto &amp; Transportation</a></h2></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/automotive-transportation-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Automotive &amp; Transportation
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/aerospace-defense-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Aerospace, Defense &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Aerospace, Defense
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/air-freight-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Air Freight &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Air Freight
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/airlines-aviation-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Airlines &amp; Aviation &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Airlines &amp; Aviation
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/automotive-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Automotive &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Automotive
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/maritime-shipbuilding-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Maritime &amp; Shipbuilding &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Maritime &amp; Shipbuilding
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/railroads-and-intermodal-transportation-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Railroads and Intermodal Transportation &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Railroads and Intermodal Transportation
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/supply-chain-logistics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Supply Chain/Logistics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Supply Chain/Logistics
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/transportation-trucking-railroad-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Transportation, Trucking &amp; Railroad &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Transportation, Trucking &amp; Railroad
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/travel-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Travel &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Travel
        </a></li><li><a class="omniture-subnav" href="/news-releases/automotive-transportation-latest-news/trucking-and-road-transportation-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Trucking and Road Transportation &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Trucking and Road Transportation
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/automotive-transportation-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | Auto &amp; Transportation Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Auto &amp; Transportation Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/automotive-transportation-latest-news/automotive-transportation-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Auto &amp; Transportation | View All Auto &amp; Transportation  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Auto &amp; Transportation </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/business-technology-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Business&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Business Technology</a></h2></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/business-technology-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Business Technology
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/blockchain-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Blockchain &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Blockchain
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/broadcast-tech-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Broadcast Tech &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Broadcast Tech
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/computer-electronics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Computer &amp; Electronics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Computer &amp; Electronics
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/computer-hardware-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Computer Hardware &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Computer Hardware
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/computer-software-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Computer Software &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Computer Software
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/data-analytics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Data Analytics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Data Analytics
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/electronic-commerce-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Electronic Commerce &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Electronic Commerce
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/electronic-components-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Electronic Components &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Electronic Components
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/electronic-design-automation-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Electronic Design Automation &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Electronic Design Automation
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/financial-technology-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Financial Technology &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Financial Technology
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/high-tech-security-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | High Tech Security &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">High Tech Security
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/internet-technology-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Internet Technology &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Internet Technology
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/nanotechnology-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Nanotechnology &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Nanotechnology
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/networks-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Networks &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Networks
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/peripherals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Peripherals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Peripherals
        </a></li><li><a class="omniture-subnav" href="/news-releases/business-technology-latest-news/semiconductors-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Semiconductors &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Semiconductors
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/business-technology-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | Business Technology Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Business Technology Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/business-technology-latest-news/business-technology-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Business Technology | View All Business Technology  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Business Technology </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/entertainment-media-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Business&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Entertain­ment &amp; Media</a></h2></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/entertainment-media-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Entertain­ment &amp; Media
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/advertising-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Advertising &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Advertising
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/art-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Art &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Art
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/books-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Books &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Books
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/entertainment-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Entertainment &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Entertainment
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/film-and-motion-picture-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Film and Motion Picture &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Film and Motion Picture
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/magazines-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Magazines &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Magazines
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/music-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Music &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Music
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/publishing-information-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Publishing &amp; Information Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Publishing &amp; Information Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/radio-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Radio &amp; Podcast &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Radio &amp; Podcast
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/television-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Television &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Television
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/entertainment-media-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | Entertain­ment &amp; Media Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Entertain­ment &amp; Media Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/entertainment-media-latest-news/entertainment-media-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Entertain­ment &amp; Media | View All Entertain­ment &amp; Media  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Entertain­ment &amp; Media </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/financial-services-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Business&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Financial Services &amp; Investing</a></h2></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/financial-services-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Financial Services &amp; Investing
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/accounting-news-issues-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Accounting News &amp; Issues &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Accounting News &amp; Issues
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/acquisitions-mergers-and-takeovers-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Acquisitions, Mergers and Takeovers &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Acquisitions, Mergers and Takeovers
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/banking-financial-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Banking &amp; Financial Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Banking &amp; Financial Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/bankruptcy-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Bankruptcy &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Bankruptcy
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/bond-stock-ratings-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Bond &amp; Stock Ratings &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Bond &amp; Stock Ratings
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/conference-call-announcements-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Conference Call Announcements &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Conference Call Announcements
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/contracts-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Contracts &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Contracts
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/cryptocurrency-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Cryptocurrency &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Cryptocurrency
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/dividends-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Dividends &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Dividends
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/earnings-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Earnings &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Earnings
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/earnings-forecasts-projections-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Earnings Forecasts &amp; Projections &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Earnings Forecasts &amp; Projections
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/financing-agreements-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Financing Agreements &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Financing Agreements
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/insurance-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Insurance &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Insurance
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/investment-opinions-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Investments Opinions &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Investments Opinions
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/joint-ventures-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Joint Ventures &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Joint Ventures
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/mutual-funds-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Mutual Funds &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mutual Funds
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/private-placement-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Private Placement &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Private Placement
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/real-estate-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Real Estate &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Real Estate
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/restructuring-recapitalization-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Restructuring &amp; Recapitalization &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Restructuring &amp; Recapitalization
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/sales-reports-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Sales Reports &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Sales Reports
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/shareholder-activism-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Shareholder Activism &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Shareholder Activism
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/shareholder-meetings-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Shareholder Meetings &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Shareholder Meetings
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/stock-offering-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Stock Offering &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Stock Offering
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/stock-split-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Stock Split &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Stock Split
        </a></li><li><a class="omniture-subnav" href="/news-releases/financial-services-latest-news/venture-capital-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Venture Capital &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Venture Capital
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/financial-services-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | Financial Services &amp; Investing Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Financial Services &amp; Investing Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/financial-services-latest-news/financial-services-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | Financial Services &amp; Investing | View All Financial Services &amp; Investing  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Financial Services &amp; Investing </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/general-business-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Business&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">General Business</a></h2></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/general-business-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All General Business
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/awards-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Awards &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Awards
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/commercial-real-estate-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Commercial Real Estate &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Commercial Real Estate
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/corporate-expansion-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Corporate Expansion &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Corporate Expansion
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/earnings-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Earnings &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Earnings
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/environmental-social-governance-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Environmental, Social and Governance (ESG) &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Environmental, Social and Governance (ESG)
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/human-resource-workforce-management-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Human Resource &amp; Workforce Management &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Human Resource &amp; Workforce Management
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/licensing-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Licensing &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Licensing
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/new-products-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | New Products &amp; Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">New Products &amp; Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/obituaries-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Obituaries &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Obituaries
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/outsourcing-businesses-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Outsourcing Businesses &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Outsourcing Businesses
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/personnel-announcements-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Personnel Announcements &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Personnel Announcements
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/real-estate-transactions-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Real Estate Transactions &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Real Estate Transactions
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/residential-real-estate-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Residential Real Estate &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Residential Real Estate
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/small-business-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Small Business Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Small Business Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/socially-responsible-investing-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Socially Responsible Investing &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Socially Responsible Investing
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/surveys-polls-and-research-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Surveys, Polls and Research &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Surveys, Polls and Research
        </a></li><li><a class="omniture-subnav" href="/news-releases/general-business-latest-news/trade-show-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | Trade Show News &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Trade Show News
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/general-business-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | General Business Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">General Business Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/general-business-latest-news/general-business-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Business | General Business | View All General Business  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All General Business </a></h2></li></ul>
    </li>
</ul>
                
              
            </li>
          
        
          
          
          
            <li class="nav-dropdown dropdown fw nav-title">
              <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" tabindex="0" aria-expanded="false" aria-controls="3-submenu" title="Science &amp; Tech"> Science &amp; Tech </a>
              
              
                
                  
                  <ul class="dropdown-menu tier-three">
    <li class="row">
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/consumer-technology-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Science &amp; Tech&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Consumer Technology</a></h2></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/consumer-technology-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Consumer Technology
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/artificial-intelligence-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Artificial Intelligence &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Artificial Intelligence
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/blockchain-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Blockchain &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Blockchain
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/cloud-computing-internet-of-things-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Cloud Computing/Internet of Things &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Cloud Computing/Internet of Things
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/computer-electronics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Computer Electronics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Computer Electronics
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/computer-hardware-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Computer Hardware &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Computer Hardware
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/computer-software-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Computer Software &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Computer Software
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/consumer-electronics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Consumer Electronics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Consumer Electronics
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/cryptocurrency-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Cryptocurrency &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Cryptocurrency
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/data-analytics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Data Analytics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Data Analytics
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/electronic-commerce-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Electronic Commerce &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Electronic Commerce
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/electronic-gaming-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Electronic Gaming &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Electronic Gaming
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/financial-technology-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Financial Technology &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Financial Technology
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/mobile-entertainment-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Mobile Entertainment &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mobile Entertainment
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/multimedia-internet-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Multimedia &amp; Internet &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Multimedia &amp; Internet
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/peripherals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Peripherals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Peripherals
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/social-media-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Social Media &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Social Media
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/science-tech-engineering-math-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | STEM (Science, Tech, Engineering, Math) &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">STEM (Science, Tech, Engineering, Math)
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/supply-chain-logistics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Supply Chain/Logistics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Supply Chain/Logistics
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-technology-latest-news/wireless-communications-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Wireless Communications &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Wireless Communications
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/consumer-technology-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | Consumer Technology Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Consumer Technology Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/consumer-technology-latest-news/consumer-technology-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Consumer Technology | View All Consumer Technology  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Consumer Technology </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/energy-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Science &amp; Tech&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Energy &amp; Natural Resources</a></h2></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/energy-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Energy
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/alternative-energies-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Alternative Energies &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Alternative Energies
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/chemical-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Chemical &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Chemical
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/electrical-utilities-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Electrical Utilities &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Electrical Utilities
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/gas-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Gas &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Gas
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/general-manufacturing-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | General Manufacturing &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">General Manufacturing
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/mining-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Mining &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mining
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/mining-metals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Mining &amp; Metals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mining &amp; Metals
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/oil-energy-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Oil &amp; Energy &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Oil &amp; Energy
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/oil-and-gas-discoveries-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Oil and Gas Discoveries &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Oil and Gas Discoveries
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/utilities-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Utilities &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Utilities
        </a></li><li><a class="omniture-subnav" href="/news-releases/energy-latest-news/water-utilities-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Water Utilities &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Water Utilities
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/energy-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | Energy &amp; Natural Resources Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Energy &amp; Natural Resources Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/energy-latest-news/energy-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Energy &amp; Natural Resources | View All Energy &amp; Natural Resources  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Energy &amp; Natural Resources </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/environment-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Science &amp; Tech&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Environ­ment</a></h2></li><li><a class="omniture-subnav" href="/news-releases/environment-latest-news/environment-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Environ­ment
        </a></li><li><a class="omniture-subnav" href="/news-releases/environment-latest-news/conservation-recycling-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | Conservation &amp; Recycling &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Conservation &amp; Recycling
        </a></li><li><a class="omniture-subnav" href="/news-releases/environment-latest-news/environmental-issues-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | Environmental Issues &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Environmental Issues
        </a></li><li><a class="omniture-subnav" href="/news-releases/environment-latest-news/environmental-policy-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | Environmental Policy &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Environmental Policy
        </a></li><li><a class="omniture-subnav" href="/news-releases/environment-latest-news/environmental-products-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | Environmental Products &amp; Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Environmental Products &amp; Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/environment-latest-news/green-technology-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | Green Technology &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Green Technology
        </a></li><li><a class="omniture-subnav" href="/news-releases/environment-latest-news/natural-disasters/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | Natural Disasters &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Natural Disasters
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/environment-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | Environ­ment Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Environ­ment Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/environment-latest-news/environment-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Environ­ment | View All Environ­ment  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Environ­ment </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/heavy-industry-manufacturing-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Science &amp; Tech&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Heavy Industry &amp; Manufacturing</a></h2></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/heavy-industry-manufacturing-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Heavy Industry &amp; Manufacturing
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/aerospace-defense-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Aerospace &amp; Defense &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Aerospace &amp; Defense
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/agriculture-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Agriculture &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Agriculture
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/chemical-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Chemical &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Chemical
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/construction-building-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Construction &amp; Building &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Construction &amp; Building
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/general-manufacturing-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | General Manufacturing &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">General Manufacturing
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/hvac-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | HVAC (Heating, Ventilation and Air-Conditioning) &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">HVAC (Heating, Ventilation and Air-Conditioning)
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/machinery-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Machinery &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Machinery
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/machine-tools-metalworking-and-metallury-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Machine Tools, Metalworking and Metallurgy &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Machine Tools, Metalworking and Metallurgy
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/mining-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Mining &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mining
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/mining-metals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Mining &amp; Metals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mining &amp; Metals
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/paper-forest-products-containers-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Paper, Forest Products &amp; Containers &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Paper, Forest Products &amp; Containers
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/precious-metals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Precious Metals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Precious Metals
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/textiles-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Textiles &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Textiles
        </a></li><li><a class="omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/tobacco-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Tobacco &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Tobacco
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | Heavy Industry &amp; Manufacturing Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Heavy Industry &amp; Manufacturing Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/heavy-industry-manufacturing-latest-news/heavy-industry-manufacturing-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Heavy Industry &amp; Manufacturing | View All Heavy Industry &amp; Manufacturing  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Heavy Industry &amp; Manufacturing </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/telecommunications-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Science &amp; Tech&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Telecomm­unications</a></h2></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/telecommunications-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Telecomm­unications
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/carriers-and-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Carriers and Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Carriers and Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/mobile-entertainment-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Mobile Entertainment &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mobile Entertainment
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/networks-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Networks &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Networks
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/peripherals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Peripherals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Peripherals
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/telecommunications-equipment-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Telecommunications Equipment &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Telecommunications Equipment
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/telecommunications-industry-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Telecommunications Industry &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Telecommunications Industry
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/voip-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | VoIP (Voice over Internet Protocol) &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">VoIP (Voice over Internet Protocol)
        </a></li><li><a class="omniture-subnav" href="/news-releases/telecommunications-latest-news/wireless-communications-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Wireless Communications &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Wireless Communications
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/telecommunications-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | Telecomm­unications Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Telecomm­unications Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/telecommunications-latest-news/telecommunications-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Science &amp; Tech | Telecomm­unications | View All Telecomm­unications  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Telecomm­unications </a></h2></li></ul>
    </li>
</ul>
                
              
            </li>
          
        
          
          
          
            <li class="nav-dropdown dropdown fw nav-title">
              <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" tabindex="0" aria-expanded="false" aria-controls="4-submenu" title="Lifestyle &amp; Health"> Lifestyle &amp; Health </a>
              
              
                
                  
                  <ul class="dropdown-menu tier-three">
    <li class="row">
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/consumer-products-retail-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Lifestyle &amp; Health&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Consumer Products &amp; Retail</a></h2></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/consumer-products-retail-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Consumer Products &amp; Retail
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/animals-pets-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Animals &amp; Pets &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Animals &amp; Pets
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/beers-wines-and-spirits-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Beers, Wines and Spirits &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Beers, Wines and Spirits
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/beverages-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Beverages &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Beverages
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/bridal-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Bridal Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Bridal Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/cannabis-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Cannabis &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Cannabis
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/cosmetics-and-personal-care-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Cosmetics and Personal Care &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Cosmetics and Personal Care
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/fashion-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Fashion &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Fashion
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/food-beverages-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Food &amp; Beverages &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Food &amp; Beverages
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/furniture-and-furnishings-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Furniture and Furnishings &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Furniture and Furnishings
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/home-improvements-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Home Improvement &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Home Improvement
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/household-consumer-cosmetics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Household, Consumer &amp; Cosmetics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Household, Consumer &amp; Cosmetics
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/household-products-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Household Products &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Household Products
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/jewelry-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Jewelry &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Jewelry
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/non-alcoholic-beverages-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Non-Alcoholic Beverages &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Non-Alcoholic Beverages
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/office-products-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Office Products &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Office Products
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/organic-food-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Organic Food &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Organic Food
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/product-recalls-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Product Recalls &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Product Recalls
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/restaurants-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Restaurants &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Restaurants
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/retail-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Retail &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Retail
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/supermarkets-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Supermarkets &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Supermarkets
        </a></li><li><a class="omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/toys-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Toys &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Toys
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | Consumer Products &amp; Retail Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Consumer Products &amp; Retail Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/consumer-products-retail-latest-news/consumer-products-retail-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Consumer Products &amp; Retail | View All Consumer Products &amp; Retail  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Consumer Products &amp; Retail </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/entertainment-media-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Lifestyle &amp; Health&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Entertain­ment &amp; Media</a></h2></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/entertainment-media-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Entertain­ment &amp; Media
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/advertising-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Advertising &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Advertising
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/art-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Art &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Art
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/books-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Books &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Books
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/entertainment-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Entertainment &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Entertainment
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/film-and-motion-picture-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Film and Motion Picture &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Film and Motion Picture
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/magazines-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Magazines &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Magazines
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/music-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Music &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Music
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/publishing-information-services-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Publishing &amp; Information Services &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Publishing &amp; Information Services
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/radio-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Radio &amp; Podcast &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Radio &amp; Podcast
        </a></li><li><a class="omniture-subnav" href="/news-releases/entertainment-media-latest-news/television-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Television &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Television
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/entertainment-media-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | Entertain­ment &amp; Media Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Entertain­ment &amp; Media Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/entertainment-media-latest-news/entertainment-media-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Entertain­ment &amp; Media | View All Entertain­ment &amp; Media  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Entertain­ment &amp; Media </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/health-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Lifestyle &amp; Health&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Health</a></h2></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/health-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Health
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/biometrics-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Biometrics &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Biometrics
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/biotechnology-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Biotechnology &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Biotechnology
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/clinical-trials-medical-discoveries-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Clinical Trials &amp; Medical Discoveries &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Clinical Trials &amp; Medical Discoveries
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/dentistry-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Dentistry &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Dentistry
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/fda-approval-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | FDA Approval &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">FDA Approval
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/fitness-wellness-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Fitness/Wellness &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Fitness/Wellness
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/health-care-hospitals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Health Care &amp; Hospitals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Health Care &amp; Hospitals
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/health-insurance-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Health Insurance &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Health Insurance
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/infection-control-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Infection Control &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Infection Control
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/international-medical-approval-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | International Medical Approval &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">International Medical Approval
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/medical-equipment-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Medical Equipment &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Medical Equipment
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/medical-pharmaceuticals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Medical Pharmaceuticals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Medical Pharmaceuticals
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/mental-health-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Mental Health &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Mental Health
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/pharmaceuticals-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Pharmaceuticals &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Pharmaceuticals
        </a></li><li><a class="omniture-subnav" href="/news-releases/health-latest-news/supplementary-medicine-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Supplementary Medicine &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Supplementary Medicine
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/health-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | Health Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Health Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/health-latest-news/health-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Health | View All Health  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Health </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/sports-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Lifestyle &amp; Health&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Sports</a></h2></li><li><a class="omniture-subnav" href="/news-releases/sports-latest-news/sports-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Sports |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Sports
        </a></li><li><a class="omniture-subnav" href="/news-releases/sports-latest-news/general-sports-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Sports | General Sports &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">General Sports
        </a></li><li><a class="omniture-subnav" href="/news-releases/sports-latest-news/outdoors-camping-hiking-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Sports | Outdoors, Camping &amp; Hiking &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Outdoors, Camping &amp; Hiking
        </a></li><li><a class="omniture-subnav" href="/news-releases/sports-latest-news/sporting-events-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Sports | Sporting Events &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Sporting Events
        </a></li><li><a class="omniture-subnav" href="/news-releases/sports-latest-news/sports-equipment-accessories-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Sports | Sports Equipment &amp; Accessories &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Sports Equipment &amp; Accessories
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/sports-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Sports | Sports Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Sports Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/sports-latest-news/sports-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Sports | View All Sports  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Sports </a></h2></li></ul>
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/travel-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Lifestyle &amp; Health&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Travel</a></h2></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/travel-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Travel
        </a></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/amusement-parks-and-tourist-attractions-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Amusement Parks and Tourist Attractions &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Amusement Parks and Tourist Attractions
        </a></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/gambling-casinos-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Gambling &amp; Casinos &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Gambling &amp; Casinos
        </a></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/hotels-and-resorts-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Hotels and Resorts &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Hotels and Resorts
        </a></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/leisure-tourism-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Leisure &amp; Tourism &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Leisure &amp; Tourism
        </a></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/outdoors-camping-hiking-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Outdoors, Camping &amp; Hiking &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Outdoors, Camping &amp; Hiking
        </a></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/passenger-aviation-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Passenger Aviation &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Passenger Aviation
        </a></li><li><a class="omniture-subnav" href="/news-releases/travel-latest-news/travel-industry-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Travel Industry &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Travel Industry
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/travel-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | Travel Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Travel Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/travel-latest-news/travel-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Lifestyle &amp; Health | Travel | View All Travel  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Travel </a></h2></li></ul>
    </li>
</ul>
                
              
            </li>
          
        
          
          
          
            <li class="nav-dropdown dropdown fw nav-title">
              <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" tabindex="0" aria-expanded="false" aria-controls="5-submenu" title="Policy &amp; Public Interest"> Policy &amp; Public Interest </a>
              
              
                
                  
                  <ul class="dropdown-menu tier-three">
    <li class="row">
        <ul class="nav-tier">
                                                        <li><h2><a href="/news-releases/policy-public-interest-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;Policy &amp; Public Interest&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Policy &amp; Public Interest</a></h2></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/policy-public-interest-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All Policy &amp; Public Interest
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/advocacy-group-opinion-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Advocacy Group Opinion &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Advocacy Group Opinion
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/animal-welfare-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Animal Welfare &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Animal Welfare
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/canadian-federal-government-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Canadian Federal Government &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Canadian Federal Government
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/canadian-municipal-government-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Canadian Municipal Government &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Canadian Municipal Government
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/canadian-provincial-government-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Canadian Provincial Government &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Canadian Provincial Government
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/corporate-social-responsibility-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Corporate Social Responsibility &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Corporate Social Responsibility
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/domestic-policy-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Domestic Policy &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Domestic Policy
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/economic-news-trends-analysis-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Economic News, Trends, Analysis &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Economic News, Trends, Analysis
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/education-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Education &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Education
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/environmental-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Environmental &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Environmental
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/european-government-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | European Government &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">European Government
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/fda-approval-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | FDA Approval &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">FDA Approval
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/federal-and-state-legislation-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Federal and State Legislation &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Federal and State Legislation
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/federal-executive-branch-agency-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Federal Executive Branch &amp; Agency &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Federal Executive Branch &amp; Agency
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/foreign-policy-international-affairs-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Foreign Policy &amp; International Affairs &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Foreign Policy &amp; International Affairs
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/homeland-security-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Homeland Security &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Homeland Security
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/labor-union-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Labor &amp; Union &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Labor &amp; Union
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/legal-issues-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Legal Issues &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Legal Issues
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/natural-disasters-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Natural Disasters &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Natural Disasters
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/not-for-profit-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Not For Profit &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Not For Profit
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/patent-law-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Patent Law &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Patent Law
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/public-safety-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Public Safety &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Public Safety
        </a></li><li><a class="omniture-subnav" href="/news-releases/policy-public-interest-latest-news/trade-policy-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Trade Policy &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Trade Policy
        </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/policy-public-interest-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | Policy &amp; Public Interest Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Policy &amp; Public Interest Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/policy-public-interest-latest-news/policy-public-interest-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | Policy &amp; Public Interest | Policy &amp; Public Interest | View All Policy &amp; Public Interest  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">View All Policy &amp; Public Interest </a></h2></li></ul>
    </li>
</ul>
                
              
            </li>
          
        
          
          
          
            <li class="nav-dropdown dropdown fw nav-title">
              <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" tabindex="0" aria-expanded="false" aria-controls="6-submenu" title="People &amp; Culture"> People &amp; Culture </a>
              
              
                
                  
                  <ul class="dropdown-menu tier-three">
    <li class="row"> <div class="col-sm-12">
        <ul class="nav-tier"><li><h2><a href="/news-releases/multicultural-latest-news/" class="media-heading omniture-subnav" data-omniture="{&quot;SubNavigationLink&quot;:&quot;&quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">People &amp; Culture</a></h2></li>
                                                        

            <li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/multicultural-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture |  &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">All People &amp; Culture
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/native-american-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Aboriginal, First Nations &amp; Native American &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Aboriginal, First Nations &amp; Native American
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/african-american-related-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | African American &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">African American
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/asian-related-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Asian American &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Asian American
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/children-related-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Children &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Children
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/diversity-equity-inclusion/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Diversity, Equity &amp; Inclusion &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Diversity, Equity &amp; Inclusion
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/hispanic-oriented-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Hispanic &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Hispanic
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/lesbian-gay-bisexual-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Lesbian, Gay &amp; Bisexual &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Lesbian, Gay &amp; Bisexual
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/mens-interest-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Men's Interest &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Men's Interest
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/handicapped-disabled-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | People with Disabilities &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">People with Disabilities
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/religion-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Religion &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Religion
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/senior-citizens-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Senior Citizens &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Senior Citizens
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/veterans-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Veterans &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Veterans
            </a></li><li><a class="omniture-subnav" href="/news-releases/multicultural-latest-news/women-related-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | Women &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">Women
            </a></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/multicultural-latest-news/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | People &amp; Culture Overview &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}">People &amp; Culture Overview</a></h2></li><li><h2><a class="media-heading omniture-subnav" href="/news-releases/multicultural-latest-news/multicultural-latest-news-list/" data-omniture="{&quot;SubNavigationLink&quot;:&quot;NR | People &amp; Culture | People &amp; Culture | View All People &amp; Culture &quot;,&quot;FormSubNavBar&quot;:&quot;true&quot;}"> View All People &amp; Culture</a></h2></li></ul>
    </div>
    </li>
</ul>
                
              
            </li>
          
        
        
          
            <div class="pull-right nav-subnav-buttons">
   <a class="btn btn-default adv-search pull-right" type="button" href="/search/advance-search/">Advanced Search</a>
</div>
          
        
      
      
      
      
    
  </ul>

										
									</nav>
								
									<nav class="navbar products" id="mainNav-products" style="display: none;" aria-label="products">
										
											
											

  <ul class="nav nav-pills tier-two  advsearch">
    
      
      
        
          
          
          
            <li class=" ">
              
                <a href="/amplify-platform/" class="omniture-sub-menu" title="Explore Our Platform " target="_self" aria-current="false">Explore Our Platform </a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/amplify-ai-plan-module/" class="omniture-sub-menu" title="Plan Campaigns " target="_self" aria-current="false">Plan Campaigns </a>
              
              
            </li>
          
        
          
          
            <li class=" ">
              
                <a href="/ai-press-release/" class="omniture-sub-menu" title="Create with AI " target="_self" aria-current="false">Create with AI </a>
              
              
            </li>
          
          
        
          
          
          
            <li class=" ">
              
                <a href="/pr-distribution-and-placement/" class="omniture-sub-menu" title="Distribute Press Releases " target="_self" aria-current="false">Distribute Press Releases </a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/multichannel-amplification/" class="omniture-sub-menu" title="Amplify Content " target="_self" aria-current="false">Amplify Content </a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/products/investor-relations/" class="omniture-sub-menu" title="IR" target="_self" aria-current="false">IR</a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/products/all-products/" class="omniture-sub-menu" title="All Products" target="_self" aria-current="false">All Products</a>
              
              
            </li>
          
        
      
      
      
    
  </ul>

										
									</nav>
								
									<nav class="navbar contact" id="mainNav-contact" style="display: none;" aria-label="contact">
										
											
											

  <ul class="nav nav-pills tier-two  advsearch">
    
      
      
      
        
          
          
          
            <li class=" ">
              
                <a href="/contact-us/" class="omniture-sub-menu" title="Become a Client" target="_self" aria-current="false">Become a Client</a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/request-a-demo/" class="omniture-sub-menu" title="Request a Demo" target="_self" aria-current="false">Request a Demo</a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/contact-us/editorial-bureaus/" class="omniture-sub-menu" title="Editorial Bureaus" target="_self" aria-current="false">Editorial Bureaus</a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/contact-us/partnerships/" class="omniture-sub-menu" title="Partnerships" target="_self" aria-current="false">Partnerships</a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/general-enquiries/" class="omniture-sub-menu" title="General Enquiries" target="_self" aria-current="false">General Enquiries</a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/contact-us/media-enquiries/" class="omniture-sub-menu" title="Media" target="_self" aria-current="false">Media</a>
              
              
            </li>
          
        
          
          
          
            <li class=" ">
              
                <a href="/contact-us/worldwide-offices/" class="omniture-sub-menu" title="Worldwide Offices" target="_self" aria-current="false">Worldwide Offices</a>
              
              
            </li>
          
        
      
      
    
  </ul>

										
									</nav>
								
							
						</div>
                    </div>
                </div>
    

</header>

<nav class="header-mobile navbar navbar-default navbar-fixed-top mm-slideout newswire-ca">
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar-left">
            <li>
                <a class="nav-mobile-button" href="#nav-mobile" aria-label="menu">
                    <span aria-hidden="true">
                         <i class="btr bt-bars"></i>
                    </span>
                    <span class="sr-only">Hamburger menu</span>
                </a>
            </li>
            <li>
                
    <a class="navbar-brand" href="https://www.newswire.ca/" target="_self">
        
        
            <img class="img-responsive " src="/content/dam/newswire-ca/cisionreversed_logo.svg" title="Cision Canada" alt="Cision Canada">
        
    </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right"><li class="bg-brand-secondary hidden-xs">
            
                
            
                
            
                
            
                
            
                <a class="btn-sar" href="/contact-us/" target="_blank">
                    Send a Release
                </a>
            
        </li><li>
						<!--<a href="JavaScript:void(0)" class="language-toggle lang-switcher in" id="mobile-lang-fr" data-toggle="modal" data-target="#mobile-lang-fr"  data-browser-lang="en" data-req-param-org="" data-req-url="/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html" data-req-full-url="https://www.newswire.ca/content/newswire-ca/ca/en/news-releases.detail.html/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html"  data-redirect-url="/fr/news-releases/">
							<span>
								<sly data-sly-test="true">FR</sly>
								<sly data-sly-test="false">EN</sly>
							</span>
						</a>-->
						<a href="/fr/news-releases/" class="lang-switcher in padding-lang" target="_self">
							<span>FR</span>
						</a>
					</li><li class="hidden-xs">
                <a href="/contact-us/">
                    <span aria-hidden="true">
                         <i class="btr bt-phone"></i>
                    </span>

                </a>
            </li>
            <li class="dropdown visible-xs">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-label="telephone">
                     <span aria-hidden="true">
                         <i class="btr bt-phone"></i>
                    </span>
                </a>
                <ul class="dropdown-menu contact">
<li class="hidden-xs">
	<p>Phone</p>
</li>

<li class="hidden-xs">
	<a href="javascript:void(0)" class="omniture-sticky-menu">
		<p>
			<i class="btr bt-phone"></i> 877-269-7890 from 8 AM - 10 PM ET
        
		</p>
	</a>
</li>


<li><a href="/contact-us" class="btn btn-primary btn-nav-cta hidden-xs omniture-sticky-menu">ALL CONTACT INFO</a></li>
<li class="row visible-xs">
	<div class="col-xs-5 col-vcenter">
		<p class="text-center">
			<a class="omniture-sticky-menu" href="/contact-us">Contact Cision</a>
		</p>
	</div>
	<div class="col-xs-6 col-vcenter">
		<p class="text-center">
			<a href="tel:+1-888-776-0942" class="omniture-sticky-menu"> 877-269-7890</a>
			<br>
			<span class="text-muted small">from 8 AM - 10 PM ET</span>
			</p>
		</div>
	</li>

</ul>
            </li>


		

	

	   		
 
	 <li class="hidden-xs hidden-sm hidden-md" id="mobile-searchLoggedIn">
                <a href="javascript:void(0)" data-toggle="modal" data-target="#search-modal">
                   <span aria-hidden="true">
                    <i class="btr bt-search"></i>
                </span>
                </a>
            </li>
            <li class="visible-xs visible-sm visible-md dropdown" id="mobile-searchLoggedIn1">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-label="Search">
                   <span aria-hidden="true">
                    <i class="btr bt-search"></i>
                </span>
                </a>
                <ul class="dropdown-menu search">
                    <li class="input-group">
                   		 <input type="hidden" id="mobilesitesearchurl" name="searchlink" value="/search/all/">
                        <input type="text" id="mobileSiteSearchbox" class="dropddown-menu" placeholder="Search News Releases, Organizations" aria-label="Search News Releases, Organizations">
                    </li>
                </ul>
            </li>

		

            <!--  <li class="hidden-xs hidden-sm hidden-md">
                <a href="javascript:void(0)" data-toggle="modal" data-target="#search-modal">
                    <i class="btr bt-search"></i>
                </a>
            </li>
            <li class="visible-xs visible-sm visible-md dropdown">
                <a href="#" class="dropdown-toggle"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="btr bt-search"></i>
                </a>
                <ul class="dropdown-menu search">
                    <div class="input-group">
                   		 <input type="hidden" id="mobilesitesearchurl" name="searchlink" value="/content/prnewswire/us/en/search.html">
                        <input type="text"  id="mobileSiteSearchbox" class="dropddown-menu" placeholder="">
                    </div>
                </ul>
            </li> -->
        </ul>
    </div>
</nav>

<nav id="nav-mobile" aria-label="Mobile menu" role="dialog" aria-modal="true">
    
<div id="mm-panel-default" class="Panel">
    <ul id="mm-default">
  
       
         

    
         <li class="mm-footer">
		
		<a href="https://www.newswire.ca/contact-us/" target="_self">Send a Release</a>
		
		
		</li>
    
         <li class="mm-footer">
		
		<a href="https://www.newswire.ca/contact-us/" target="_self">Sign Up</a>
		
		
		</li>
    
         <li class="mm-footer">
		
		<a href="https://www.newswire.ca/resources/" target="_self">Resources</a>
		
		
		</li>
    
         <li class="mm-footer">
		
		<a href="https://www.newswire.ca/products/investor-relations/" target="_self">Investor Relations</a>
		
		
		</li>
    
         <li class="mm-footer">
		
		
		<a href="https://prnmedia.prnewswire.com/" target="_blank">Journalists</a>
		
		</li>
    
         <li class="mm-footer">
		
		
		<a href="https://cnw.en.mediaroom.com/events" target="_blank">Webcasts</a>
		
		</li>
    
         <li class="mm-footer">
		
		<a href="https://www.newswire.ca/mycnw/login/" target="_self">my CNW</a>
		
		
		</li>
    
         <li class="mm-footer">
		
		
		<a href="https://gdpr.cision.com/" target="_blank">GDPR</a>
		
		</li>
    

<!-- <div data-sly-test="false" class="cq-placeholder" data-emptytext="edit the social component"></div>
 -->
<li class="mm-footer mm-social">


                  <a aria-label="Visit our social media page on Twitter" href="https://twitter.com/CNWGroup" target="_blank">
                    <i class="fab fab-twitter"></i>
                  </a>

                  <a aria-label="Visit our social media page on Facebook" href="https://www.facebook.com/CisionCA/" target="_blank">
                    <i class="fab fab-facebook-alt"></i>
                  </a>

                  <a aria-label="Visit our social media page on LinkedIn" href="https://www.linkedin.com/company/cnw-group" target="_blank">
                    <i class="fab fab-linkedin-alt"></i>
                  </a>

</li>
      
      
    </ul>
</div>

    
        <div id="mm-panel-news" class="Panel parent-panel">
            <ul id="mm-news" role="tabpanel" data-section="News">
                
                    
                    


    
        

            
                <!-- OverView removed from list  -->
                
            
            

            
        

            
            
                <li>
                    <span>News in Focus</span>
                    
                        
                        <ul class="tier-three" data-section="news">
  
			
                    <li>
                        <a href="/news-releases/">Browse All News
                      </a>
                    </li>
        
                    <li>
                        <a href="/news-releases/multimedia/">Multimedia Gallery
                      </a>
                    </li>
        
                    <li>
                        <a href="/news-releases/latest-news-topics/">Trending Topics
                      </a>
                    </li>
        
    
</ul>
                    
                </li>
            

            
        

            
            

            
                <li>
                    <span>Business</span>
                    
                        
                        <ul class="tier-three" data-section="news">
    
        
            
                
				  
                    <li>
                        <a href="/news-releases/automotive-transportation-latest-news/">Auto &amp; Transportation
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/business-technology-latest-news/">Business Technology
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/entertainment-media-latest-news/">Entertain­ment &amp; Media
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/financial-services-latest-news/">Financial Services &amp; Investing
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/general-business-latest-news/">General Business
                      </a>
                    </li>
				  
				  
                
            
        
    
</ul>
                    
                </li>
            
        

            
            

            
                <li>
                    <span>Science &amp; Tech</span>
                    
                        
                        <ul class="tier-three" data-section="news">
    
        
            
                
				  
                    <li>
                        <a href="/news-releases/consumer-technology-latest-news/">Consumer Technology
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/energy-latest-news/">Energy &amp; Natural Resources
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/environment-latest-news/">Environ­ment
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/heavy-industry-manufacturing-latest-news/">Heavy Industry &amp; Manufacturing
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/telecommunications-latest-news/">Telecomm­unications
                      </a>
                    </li>
				  
				  
                
            
        
    
</ul>
                    
                </li>
            
        

            
            

            
                <li>
                    <span>Lifestyle &amp; Health</span>
                    
                        
                        <ul class="tier-three" data-section="news">
    
        
            
                
				  
                    <li>
                        <a href="/news-releases/consumer-products-retail-latest-news/">Consumer Products &amp; Retail
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/entertainment-media-latest-news/">Entertain­ment &amp; Media
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/health-latest-news/">Health
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/sports-latest-news/">Sports
                      </a>
                    </li>
				  
				  
                
            
                
				  
                    <li>
                        <a href="/news-releases/travel-latest-news/">Travel
                      </a>
                    </li>
				  
				  
                
            
        
    
</ul>
                    
                </li>
            
        

            
            

            
                <li>
                    <span>Policy &amp; Public Interest</span>
                    
                        
                        <ul class="tier-three" data-section="news">
    
        
            
                
				  
                    <li>
                        <a href="/news-releases/policy-public-interest-latest-news/">Policy &amp; Public Interest
                      </a>
                    </li>
				  
				  
                
            
        
    
</ul>
                    
                </li>
            
        

            
            

            
                <li>
                    <span>People &amp; Culture</span>
                    
                        
                        <ul class="tier-three" data-section="news">
    
        
            
                
				  
				  
				    <li>
					  
                        <a href="/news-releases/multicultural-latest-news/">People &amp; Culture
                      </a>
					  
                    </li>
                  <!--   <li>
                        <a href="#">In-Language News
                      </a>
                    </li>
					-->
				  
                
            
        
    
</ul>
                    
                </li>
            
        
    
    






                
                
                
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/contact-us/" target="self">Send a Release</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/contact-us/" target="self">Sign Up</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/resources/" target="self">Resources</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/products/investor-relations/" target="self">Investor Relations</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://prnmedia.prnewswire.com/" target="self">Journalists</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://cnw.en.mediaroom.com/events" target="self">Webcasts</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/mycnw/login/" target="self">my CNW</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://gdpr.cision.com/" target="self">GDPR</a>
                        </li>
                    
                
                <li class="mm-footer mm-social">
                    
                        
                             <a aria-label="Visit our social media page on Twitter" href="https://twitter.com/CNWGroup" target="self">
                                <i class="fab fab-twitter"></i>
                            </a>                             
                        
                             <a aria-label="Visit our social media page on Facebook" href="https://www.facebook.com/CisionCA/" target="self">
                                <i class="fab fab-facebook-alt"></i>
                            </a>                             
                        
                             <a aria-label="Visit our social media page on LinkedIn" href="https://www.linkedin.com/company/cnw-group" target="self">
                                <i class="fab fab-linkedin-alt"></i>
                            </a>                             
                        
                    
                </li>
            </ul>
        </div>
        

   <input type="hidden" class="mobile-nav-tabs" value="News" data-link="/news-releases">
    
        <div id="mm-panel-products" class="Panel parent-panel">
            <ul id="mm-products" role="tabpanel" data-section="Products">
                
                    
                    


    
    
        
        
            
            
                
                
                    <li class="">
                        
                            <a href="/amplify-platform/" title="Explore Our Platform " target="_self">Explore Our Platform </a>
                        
                        
            </li>
        
    

            
            
                
                
                    <li class="">
                        
                            <a href="/amplify-ai-plan-module/" title="Plan Campaigns " target="_self">Plan Campaigns </a>
                        
                        
            </li>
        
    

            
            
                
                    <li class="">
                        <a href="/ai-press-release/" title="Create with AI " target="_blank">Create with AI </a>
                    </li>
                
                
    

            
            
                
                
                    <li class="">
                        
                            <a href="/pr-distribution-and-placement/" title="Distribute Press Releases " target="_self">Distribute Press Releases </a>
                        
                        
            </li>
        
    

            
            
                
                
                    <li class="">
                        
                            <a href="/multichannel-amplification/" title="Amplify Content " target="_self">Amplify Content </a>
                        
                        
            </li>
        
    

            
            
                
                
                    <li class="">
                        
                            <a href="/products/investor-relations/" title="IR" target="_self">IR</a>
                        
                        
            </li>
        
    

            
            
                
                
                    <li class="">
                        
                            <a href="/products/all-products/" title="All Products" target="_self">All Products</a>
                        
                        
            </li>
        
    








                
                
                
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/contact-us/" target="self">Send a Release</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/contact-us/" target="self">Sign Up</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/resources/" target="self">Resources</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/products/investor-relations/" target="self">Investor Relations</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://prnmedia.prnewswire.com/" target="self">Journalists</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://cnw.en.mediaroom.com/events" target="self">Webcasts</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/mycnw/login/" target="self">my CNW</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://gdpr.cision.com/" target="self">GDPR</a>
                        </li>
                    
                
                <li class="mm-footer mm-social">
                    
                        
                             <a aria-label="Visit our social media page on Twitter" href="https://twitter.com/CNWGroup" target="self">
                                <i class="fab fab-twitter"></i>
                            </a>                             
                        
                             <a aria-label="Visit our social media page on Facebook" href="https://www.facebook.com/CisionCA/" target="self">
                                <i class="fab fab-facebook-alt"></i>
                            </a>                             
                        
                             <a aria-label="Visit our social media page on LinkedIn" href="https://www.linkedin.com/company/cnw-group" target="self">
                                <i class="fab fab-linkedin-alt"></i>
                            </a>                             
                        
                    
                </li>
            </ul>
        </div>
        

   <input type="hidden" class="mobile-nav-tabs" value="Products" data-link="http://cnw.en.mediaroom.com/">
    
        <div id="mm-panel-contact" class="Panel parent-panel">
            <ul id="mm-contact" role="tabpanel" data-section="Contact">
                
                    
                    


    
    

    
        

            
            

                
                

                    
                    
                        
                            <li class="mm_selected">


                                
                                    <a href="/contact-us" title="Sign Up" target="_self">Sign Up</a>
                                
                                

                    </li>
                
                
                
            
        
    

                
                

                    
                    
                        
                            <li class="mm_selected">


                                
                                    <a href="/request-a-demo/" title="Request a Demo" target="_self">Request a Demo</a>
                                
                                

                    </li>
                
                
                
            
        
    

                
                

                    
                    
                        
                            <li class="mm_selected">


                                
                                    <a href="/contact-us/editorial-bureaus" title="Editorial Bureaus" target="_self">Editorial Bureaus</a>
                                
                                

                    </li>
                
                
                
            
        
    

                
                

                    
                    
                        
                            <li class="mm_selected">


                                
                                    <a href="/contact-us/partnerships" title="Partnerships" target="_self">Partnerships</a>
                                
                                

                    </li>
                
                
                
            
        
    

                
                

                    
                    
                        
                            <li class="mm_selected">


                                
                                    <a href="/contact-us/general-enquiries/" title="General Enquiries" target="_self">General Enquiries</a>
                                
                                

                    </li>
                
                
                
            
        
    

                
                

                    
                    
                        
                            <li class="mm_selected">


                                
                                    <a href="/contact-us/media-enquiries" title="Media Enquiries" target="_self">Media Enquiries</a>
                                
                                

                    </li>
                
                
                
            
        
    

                
                

                    
                    
                        
                            <li class="mm_selected">


                                
                                    <a href="/contact-us/worldwide-offices" title="Worldwide Offices" target="_self">Worldwide Offices</a>
                                
                                

                    </li>
                
                
                
            
        
    









                
                
                
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/contact-us/" target="self">Send a Release</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/contact-us/" target="self">Sign Up</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/resources/" target="self">Resources</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/products/investor-relations/" target="self">Investor Relations</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://prnmedia.prnewswire.com/" target="self">Journalists</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://cnw.en.mediaroom.com/events" target="self">Webcasts</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://www.newswire.ca/mycnw/login/" target="self">my CNW</a>
                        </li>
                    
                        <li class="mm-footer">
                           <a href="https://gdpr.cision.com/" target="self">GDPR</a>
                        </li>
                    
                
                <li class="mm-footer mm-social">
                    
                        
                             <a aria-label="Visit our social media page on Twitter" href="https://twitter.com/CNWGroup" target="self">
                                <i class="fab fab-twitter"></i>
                            </a>                             
                        
                             <a aria-label="Visit our social media page on Facebook" href="https://www.facebook.com/CisionCA/" target="self">
                                <i class="fab fab-facebook-alt"></i>
                            </a>                             
                        
                             <a aria-label="Visit our social media page on LinkedIn" href="https://www.linkedin.com/company/cnw-group" target="self">
                                <i class="fab fab-linkedin-alt"></i>
                            </a>                             
                        
                    
                </li>
            </ul>
        </div>
        

   <input type="hidden" class="mobile-nav-tabs" value="Contact" data-link="/contact-us">
    

</nav>
</div>   


  <main role="main" id="main">
    

    
	
    
<script src="/etc.clientlibs/prncom/clientlibs/share_clientlibs.min.js"></script>



	<input type="hidden" id="mobileImageWidth" name="mobileImageWidth" value="300">
	<input type="hidden" id="tabletImageWidth" name="tabletImageWidth" value="350">
	<input type="hidden" id="desktopImageWidth" name="desktopImageWidth" value="350">
	<input type="hidden" id="logoWidth" name="logoWidth" value="200">
	<input type="hidden" id="minCarouselWidth" name="minCarouselWidth" value="200">
	
	
		
		
			
			
				
 
  
    
    <article class="news-release inline-gallery-template">
    
    <header class="container release-header">
      <div class="custom-container">
        <div class="row">
          <div class="col-sm-12">
      
	
	
		<div class="row detail-headline">
			<div class="col-sm-8 col-vcenter col-xs-12 ">
				
					<h1>STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE
						
						
						
					</h1>
				

				
			</div>
			
				<div class="col-sm-4 col-xs-12 col-vcenter">
					<div class="image logo logo-wrapper" data-src="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?p=publish" data-asset-type="photo" data-asset-label="Logo" data-download-url="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg" data-tweet-text="Star Diamond logo (CNW Group/Star Diamond Corporation)" data-pinterest-text="Star Diamond logo (CNW Group/Star Diamond Corporation)" data-linkedin-text="Star Diamond logo (CNW Group/Star Diamond Corporation)" data-facebook-share-text="Star Diamond logo (CNW Group/Star Diamond Corporation)" data-twitter-share-url="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?p=twitter" data-facebook-share-url="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?p=facebook" data-pinterest-share-url="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?p=publish" data-linkedin-share-url="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?p=linkedin" onclick="omniture_corousal('Carousel Page','Photo Open','https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg','Logo');">
						<a role="button" href="#" class="tablogofocus">
							<img class="img-responsive" title="Star Diamond logo (CNW Group/Star Diamond Corporation)" data-getimg="https://mma.prnewswire.com/media/2468405/Star_Diamond_Corporation_STAR___ORION_SOUTH_DIAMOND_PROJECT%C2%A0REVI.jpg?w=200" alt="Star Diamond logo (CNW Group/Star Diamond Corporation)" loading="lazy"></a>
					</div>
				</div>
			
		</div>

	

</div>
          </div>
      <div class="row">
        <div class="col-sm-12">
          <hr>
        </div>
      </div>
      
	
		 
		 
		
		
		
		
			<input type="hidden" id="isWhatsApp" value="enabled">
		
		<div class="row">
			<div class="col-lg-8 col-md-8 col-sm-7 swaping-class-left">
				<h2 class="meta">News provided by</h2>
				
					
						
							
								<a href="/news/star-diamond-corporation/">
							
						
						<strong>Star Diamond Corporation
							
								
									<span aria-hidden="true" class="btb bt-long-arrow-right"></span>
								
							
							
						</strong>
						</a>
					
				
				<p class="mb-no">Jul 24, 2024, 11:06 ET</p>
			</div>
			
				<div class="col-lg-4 col-md-4 col-sm-5 swaping-class-right">

					<div class="social-share-circle pull-right hidden-xs">
						<h2 class="meta text-uppercase mb-s">Share this article</h2>
						<div class="social-links">
							<ul class="list-unstyled">
								
									<a href="javascript:;" class="btn-facebook" aria-label="facebook sharing" onclick="sharing_url('facebook','top nav','www.newswire.ca')">
										<li class="social-facebook">
											<span aria-hidden="true"><i class="fab fab-facebook-alt"></i></span>
										</li>
									</a>
								
								
								<a href="javascript:;" class="btn-twitter" aria-label="twitter sharing" onclick="shareIt(this,'Twitter','top nav')" data-tweet-text="STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE" data-twitter-share-url="https://www.newswire.ca/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html">
									<li class="social-twitter">
										<span aria-hidden="true"> <i class="fab fab-twitter"></i></span>
									</li>
								</a>
								
									<a href="javascript:;" class="btn-linkedin" aria-label="linkedin sharing" onclick="sharing_url('linkedin','top nav','www.newswire.ca')">
										<li class="social-linkedin">
											<span aria-hidden="true"><i class="fab fab-linkedin-alt"></i></span>
										</li>
									</a>
									
										<a href="javascript:;" class="btn-whatsapp" aria-label="Whatsapp sharing" onclick="sharing_url('whatsapp','top nav','www.prnewswire.com')">
											<li class="social-whatsapp">
												<span aria-hidden="true"><i class="fab fab-whatsapp"></i></span>
											</li>
										</a>
									
									
										<a href="javascript:;" class="btn-pinterest" aria-label="pinterest sharing" onclick="sharing_url('pinterest','top nav','www.newswire.ca')">
											<li class="social-pinterest">
												<span aria-hidden="true"><i class="fab fab-pinterest"></i></span>
											</li>
										</a>
									
								
								
								
								<a class="hidden-xs btn-email" href="javascript:;" aria-label="email sharing" onclick="sharing_url('Email','top nav','www.newswire.ca')">
									<li>
										<span aria-hidden="true"> <i class="bts bt-envelope"></i></span>
									</li>
								</a>
							</ul>
							<div class="weixinTC hidden">
								<div class="TCtop " id="qrCode"><span class="TCtopLeft">Share to</span><span class="TCtopRight"><span class="TCtopClose" onclick="weChatHide()">X</span></span></div>
								<div class="TCimg"><img src="" data-src=""></div>
							</div>
						</div>
						
					</div>
				</div>
				<!-- Button trigger modal -->
				<a type="button" class="btn btn-fab visible-xs" data-toggle="modal" data-target="#social-share-mobile"> <i class="btr bt-share"></i>
				</a>
				<!-- Modal -->
				<div class="modal fade modal-bottom social-share-mobile" id="social-share-mobile" tabindex="-1" role="dialog" aria-labelledby="social-share-mobile-label">
					<div class="modal-dialog" role="document">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<i class="btr bt-times"></i>
						</button>
						<div class="modal-content">
							<div class="modal-body">
								<p class="meta text-uppercase mb-s">Share this article</p>
								<div class="social-links">
									<ul class="list-unstyled">
										
											<a href="javascript:;" onclick="sharing_url('facebook','','www.newswire.ca')">
												<li class="social-facebook"><i class="fab fab-facebook-alt"></i></li>
											</a>
											<a href="javascript:;" class="btn-twitter__mobile" onclick="shareIt(this,'Twitter','top nav')" data-tweet-text="STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE" data-twitter-share-url="https://www.newswire.ca/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html">
												<li class="social-twitter"><i class="fab fab-twitter"></i>
												</li>
											</a>
											<a href="javascript:;" onclick="sharing_url('linkedin','','www.newswire.ca')">
												<li class="social-linkedin"><i class="fab fab-linkedin-alt"></i></li>
											</a>
											
												<a href="javascript:;" class="btn-whatsapp" aria-label="Whatsapp sharing" onclick="sharing_url('whatsapp','top nav','www.prnewswire.com')">
													<li class="social-whatsapp">
														<span aria-hidden="true"><i class="fab fab-whatsapp"></i></span>
													</li>
												</a>
											
											
												<a href="javascript:;" onclick="sharing_url('pinterest','','www.newswire.ca')">
													<li class="social-pinterest"><i class="fab fab-pinterest"></i>
													</li>
												</a>
											
										
										
										
									</ul>
									<div class="weixinTC hidden">
										<div class="TCtop " id="qrCodeMobile"><span class="TCtopLeft">Share to</span><span class="TCtopRight"><span class="TCtopClose" onclick="weChatMobHide()">X</span></span></div>
										<div class="TCimg"><img src="" data-src=""></div>
									</div>
								</div>
								
							</div>
						</div>
					</div>
				</div>
			
		</div>
	

      <div class="row">
        <div class="col-sm-12 col-xs-12">
          <hr>
        </div>
      </div>
          </div>
    </header>
    <section class="release-body container ">
      <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
          
		  
          
            
            
            <p class="prntac"><b>TOTAL INDICATED: 72 MILLION CARATS, TOTAL INFERRED: 15 MILLION CARATS</b></p>
<p class="prntal"><b><span>Stock Symbol: DIAM: TSX&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></b></p>
<p><span class="legendSpanClass"><span class="xn-location">SASKATOON, SK</span></span>, <span class="legendSpanClass"><span class="xn-chron">July 24, 2024</span></span> /CNW/ - Star Diamond Corporation ("Star Diamond" or the "Company") is pleased to announce a significant increase in the estimated Mineral Resources for the Star - Orion South Diamond Project (the "Project").</p>
<p><b>Highlights</b></p>
<ul type="disc">
 <li><b>Indicated Mineral Resources on Star have increased 22 percent</b>&nbsp;to 34.8 million carats and the grade has increased 20 percent to 19.4 cpht</li>
 <li><b>Indicated Mineral Resources on Orion South have increased 37 percent</b>&nbsp;to 36.9 million carats and the grade has increased 32 percent to 17.9 cpht</li>
 <li><b><span class="xn-person">Star Diamond</span> has determined that no additional bulk sampling is required</b>&nbsp;<b>on the Orion South Kimberlite</b> for the rigorous estimation of these Mineral Resources, and this results in the savings of millions of dollars in exploration expenditures and shaves significant time off the completion of the Pre-Feasibility Study ("PFS").</li>
</ul>
<p><b>President &amp; CEO, <span class="xn-person">Ewan Mason</span> </b>said:<b> "</b>Our technical team and outside consultants have been working extremely hard for the last year and a half to arrive at this incredible outcome.&nbsp; Not only has the requirement for a bulk sample costing tens of millions of dollars been removed but we have reduced the time to complete a Feasibility Study significantly.&nbsp; We intend to have a Feasibility Study completed by the end of 2026, with hopes that shovels could be in the ground within 3-5 years, subject to project financing, permitting and updated environmental approvals. Additionally, such a significant increase in grade and total carats across both pipes bodes well for project economics.&nbsp; It is full speed ahead on the PFS".</p>
<p><b>Revised Mineral Resources Estimate</b></p>
<p><b>Table 1. Revised Mineral Resources Estimates for the Star and Orion South Kimberlites </b></p>
<div>
 <div class="divOverflow">
  <div class="table-responsive">
   <table border="0" cellpadding="1" cellspacing="0" class="prnbcc" width="">
    <tbody>
     <tr>
      <td class="prnpr2 prnpl2 prnvab prntal prncbts prnbrbrs prnbbbs prnbsbls" colspan="5" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Star Kimberlite </b></span></p> <p class="prnml4 dnr"><span class="prnews_span"><b>Revised Mineral Resources Estimate</b></span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prnpr2 prnpl2 prnvab prntal prncbts prnbrbrs prnbbbs prnsblb1" colspan="5" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Orion South Kimberlite</b></span></p> <p class="prnml4 dnr"><span class="prnews_span"><b>Revised Mineral Resources Estimate</b></span></p> </td>
     </tr>
     <tr>
      <td class="prnpr2 prnpl2 prnvab prntac prnsbtb1 prnbrbrs prnbbbs prnbsbls" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Resource <br class="dnr">Category</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Kimberlite <br class="dnr">Unit</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Tonnes <br class="dnr">x1,000</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Grade <br class="dnr">cpht</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Carats <br class="dnr">x1,000</b></span></p> </td>
      <td class="prnpr2 prnpl2 prnvab prntac prnsbtb1 prnbrbrs prnsbbb1 prnsblb1" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Resource <br class="dnr">Category</b></span></p> </td>
      <td class="prngen8" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Kimberlite <br class="dnr">Unit</b></span></p> </td>
      <td class="prngen8" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Tonnes <br class="dnr">x1,000</b></span></p> </td>
      <td class="prngen8" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Grade <br class="dnr">cpht</b></span></p> </td>
      <td class="prngen8" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Carats <br class="dnr">x1,000</b></span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">MJF</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">21,822</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">6.6</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">1,437</span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">EJF Outer</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">46,673</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">16.3</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">7,593</span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">EJF Outer</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">47,659</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">16.9</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">8,045</span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">EJF Inner</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">94,177</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">25.7</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">24,219</span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">EJF Inner</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">84,090</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">24.0</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">20,168</span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Pense</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">65,746</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">7.8</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">5,125</span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Pense</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">13,960</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">18.1</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">2,525</span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Indicated</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>TOTAL</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>206,596</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>17.9</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>36,937</b></span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Indicated</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Cantuar</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">12,060</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">21.7</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">2,622</span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Inferred</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">EJF Outer</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">41,236</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">15.5</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">6,400</span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Indicated</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>TOTAL</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>179,591</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>19.4</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>34,797</b></span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Inferred</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Pense</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">2,591</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">7.5</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">194</span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Inferred</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">EJF Outer</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">34,100</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">14.4</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">4,923</span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Inferred</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">P3</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">6,093</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">12.2</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">742</span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Inferred</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Pense</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">9,982</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">17.6</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">1,761</span></p> </td>
      <td class="prngen3" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen11" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Inferred</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>TOTAL</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>49,921</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>14.7</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>7,336</b></span></p> </td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Inferred</span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">Cantuar</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">5,488</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">21.0</span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span">1,154</span></p> </td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen13" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
     </tr>
     <tr>
      <td class="prngen9" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>Inferred</b></span></p> </td>
      <td class="prngen6" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>TOTAL</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>49,570</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>15.8</b></span></p> </td>
      <td class="prngen10" colspan="1" rowspan="1" height="" width=""><p class="prnml4 dnr"><span class="prnews_span"><b>7,838</b></span></p> </td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen13" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
      <td class="prngen12" colspan="1" rowspan="1" height="" width=""><br class="dnr"></td>
     </tr>
    </tbody>
   </table>
  </div>
 </div>
</div>
<p><b>Table Notes Apply to Table 1&nbsp;</b></p>
<ol type="1">
 <li>Canadian Institute of Mining and Metallurgy ("CIM")&nbsp;definitions were followed for classification of mineral resources.</li>
 <li>Star Kimberlite Units:&nbsp;Cantuar, <span class="xn-location">Pense</span>, Early Joli Fou ("EJF"), &amp; Mid Joli Fou ("MJF").</li>
 <li>Orion South Kimberlite Units: P3, Pense &amp; Early Joli Fou (EJF). &nbsp;</li>
 <li>Mineral Resources are constrained within a Whittle optimized pit shell.</li>
 <li>Mineral Resources, which are not Mineral Reserves do not have demonstrated economic viability. The estimation of Mineral Resources may be materially affected by environmental, permitting, legal, title, taxation, socio-political, marketing or other relevant issues.</li>
 <li>There is no guarantee that all or any part of the Mineral Resources will be converted into a Mineral Reserves.</li>
 <li>Grade values are rounded to the first decimal.</li>
 <li>The effective date of the Revised Mineral Resources estimate is <span class="xn-chron">July 24, 2024</span>.</li>
 <li>The EJF Inner and Outer kimberlite units for both deposits are based on detailed kimberlite geology recorded from the core logging of the pattern drilling program. The&nbsp;EJF Inner represents coarser grained EJF kimberlite that occurs within the volcanic crater and the EJF Outer includes finer grained EJF kimberlite that lies on and outside the crater rim. This Revised Mineral Resources estimate acknowledges that the transition from Inner to Outer is geologically gradational.</li>
</ol>
<p><b>Senior Vice President Corporate Development, <span class="xn-person">George Read</span> </b>said:&nbsp;"<span class="xn-person">Star Diamond</span> is very pleased with the substantial increase in grade and carats in the Indicated Resource category of this Revised Mineral Resources estimate, which has been rigorously prepared to diamond industry standards using meticulously reviewed datasets. Revised diamond grade estimates are assigned to the Company's established geological models for the Star and Orion South diamond deposits using robust parameters consistent with previous studies. Rio Tinto Exploration Canada's ("RTEC") successful development and execution of the Trench Cutter ("TC") sampling program and diamond recovery in the modern Consulmet Bulk Sample Plant, generated a diamond parcel that can be integrated with diamond parcels from previous underground bulk sampling and LDD programs. The TC diamond parcel has improved the overall diamond grade and Size Frequency Distribution ("SFD") used by <span class="xn-person">Star Diamond</span> to estimate the revised Mineral Resources of both Star and Orion South. The consequent reduction in the average diamond price due to the addition of smaller stones from enhanced recovery, is significantly offset by the larger grade increase. We are also pleased to have diamond expert Mr. <span class="xn-person">Peter Ravenscroft</span> supervise this Mineral Resources update after the completion of RTEC's ten hole TC Program at the Star Kimberlite in 2019, as he not only brings over 40 years of diamond resource estimation expertise with some of the major diamond companies in the world, but also clearly aligns our Star - Orion South Diamond Project Mineral Resources estimate with established diamond industry standards. Estimation of these Revised Mineral Resources has taken a more pragmatic approach with careful consideration of the geological controls on diamond distribution. Particular attention has been given to variations in diamond SFD, in addition to diamond grade. This approach has resulted in a substantial increase in the Indicated Resources for both Star and Orion South. The Star – Orion South Diamond Project now has one of the largest undeveloped Indicated Resources found in any diamond project in the world. The diamond populations of the EJF and Cantuar kimberlite units at Star and the EJF kimberlite unit at Orion South have significantly coarse diamond SFD, from which we can anticipate the recovery of large, high quality (Type IIa) diamonds in future production."</p>
<p>The scientific and technical information contained in this press release has been prepared and verified by A.C.A. Howe International Limited ("Howe"),&nbsp;under the supervision of Mr.&nbsp;Daniel C. Leroux, M.Sc., P. Geo. and the Mineral Resource estimation methodology under the supervision of <span class="xn-person">Peter Ravenscroft</span>, FAusIMM, of Ravenscroft Mining Advisors, an independent mining consultant, and a Qualified Person ("QP") within the meaning of National Instrument 43-101 – Standards of Disclosure for Mineral Projects ("NI 43-101") of the Canadian Securities Administrators. This Revised Mineral Resources estimate uses diamond industry standard methods which are rigorously applied to the Star and Orion South evaluation data, acknowledging the significant control that fundamental kimberlite geology has on the distribution of diamonds within these deposits. The goal of the Revised Mineral Resources estimate was to incorporate additional detailed diamond stone size frequency information obtained by RTEC into the dataset previously used in the 2015 Mineral Resource Estimate, with particular interest in the smaller (+1, +3 &amp; +5 DTC), but valuable stones, which were inefficiently recovered in past exploration programs. Advances in processing flow sheets and updated processing technology have enabled the efficient recovery of these small diamonds by modern processing plants. The grade alignment process used by Mr. Ravenscroft in 2015 has been updated with the Star TC diamond data and subsequently applied to the Orion South Kimberlite.</p>
<p><b>Mineral Resources Estimation Methodology</b></p>
<p>Revised grade estimates at Star and Orion South have been based on a diamond industry standard approach using alignment of sample diamond size frequency distributions. &nbsp;Peter Ravenscroft explains: "This approach has allowed for the development of unbiased grade estimates that take into account the effects of using necessarily small samples in a diamond deposit with relatively low grade but coarse stone size. &nbsp;At Orion South, it has also provided a means of resolving sampling results from several sampling campaigns with different drilling methodologies and different sample plant flowsheets. &nbsp;Final alignment with underground bulk sample results and block model interpolation with appropriate smoothing has resulted in robust estimates of grade at a required level of detail for feasibility study of the Star and Orion South deposits."&nbsp;</p>
<p><b>Economic Assumptions</b></p>
<p>CIM standards and Securities Commission disclosure regulations require that a Mineral Resource can only be declared on a mineral deposit which has "reasonable prospects for eventual economic extraction". The reported Mineral Resource for Star and Orion South are constrained using a Whittle pit optimization. The Mineral Resources reported in Table 1 comprise the kimberlite that is constrained within the optimized Whittle pit shell. Diamond values for this resource statement are based on the <span class="xn-chron">June 2024</span> High modeled prices determined by in-house Diamond Specialist, <span class="xn-person">Nelson Karun</span>. This Revised Mineral Resources estimate includes only stones recovered larger than +1 DTC diamond sieve and considers all kimberlite above 90 metres above mean sea level or to a depth of 360 metres below surface in Star and 375 metres below surface in Orion South, with the surface being defined by the Digital Terrain Model.</p>
<p><b>Decision on Orion South Bulk Sampling</b></p>
<p><span class="xn-person">Star Diamond</span>, working in close consultation with <span class="xn-person">Peter Ravenscroft</span>, has determined that only limited improvements in precision could be achieved by additional, prohibitively costly bulk sample programs, and that the extensive work already completed will allow for robust diamond price estimates on both Star and Orion South, with associated confidence limits allowing for quantified risk analysis as part of the PFS. This conclusion has been reached based on the following:</p>
<ul type="disc">
 <li>Comprehensive sorting and valuation of all stones recovered from LDD and Underground sampling campaigns over the last 20 years, allowing for the combination of sample diamonds into significantly larger parcels.</li>
 <li>Detailed comparison of quality distributions between Orion South and Star, identifying some clear differences as well as some strong similarities, as would be expected from closely located kimberlites in the same cluster.</li>
 <li>Analysis of the relative precision of price estimates from samples of a different size, specifically where prices are influenced by large and high value stones as at Star and Orion South.</li>
</ul>
<p><b>Qualified Persons</b></p>
<p><span class="xn-person">Peter John Ravenscroft</span>, FAusIMM, is the owner of Ravenscroft Mining Advisors based in <span class="xn-location">Australia</span>. &nbsp;He has a Bachelor of Science degree in Mathematical Statistics from the University of <span class="xn-location">Cape Town</span> in 1979, and the equivalent of a Masters degree in Geostatistics from the Ecole des Mines de <span class="xn-location">Paris</span> in 1985. &nbsp;Peter has practised his profession for 45 years and has been directly involved in resource and reserve estimation, mine planning and project evaluation for a wide range of commodities. This includes more than ten diamond properties in <span class="xn-location">Africa</span>, <span class="xn-location">Australia</span> and <span class="xn-location">Canada</span> while working 7 years for De Beers and 17 years in technical and executive roles for Rio Tinto, where at one point he was Competent Person for all diamond operations in the company. As a result of his experience and qualifications, he is a QP as defined in NI 43–101.</p>
<p><span class="xn-person">Daniel C. Leroux</span>, M.Sc., P.Geo. is a Senior Associate Geologist of Howe's UK office. He is a member of the Association of Professional Geoscientists of <span class="xn-location">Ontario</span> ("APGO") and the Association of Professional Engineers and Geoscientists of <span class="xn-location">Saskatchewan</span> ("APEGS").&nbsp; He graduated from <span class="xn-org">Laurentian University</span> with both a Bachelor of Science degree in Geology (1993) and a Master of Science in Mineral Exploration (2013), respectively.&nbsp; Mr. Leroux has practised his profession for over 30 years,&nbsp;of which he has a total of 25 years of direct experience with diamond projects located in <span class="xn-location">Canada</span>, <span class="xn-location">Africa</span>, <span class="xn-location">Russia</span> and <span class="xn-location">South America</span>, including managerial responsibilities for all various exploration stage diamond projects from conceptual grassroots exploration projects to bulk sampling, diamond resource estimation and pre-feasibility to feasibility studies on advanced diamond projects.&nbsp; As a result of his experience and qualifications, he is a QP as defined in NI 43–101.</p>
<p><b>Next Steps</b></p>
<p><span class="xn-person">Star Diamond</span> will file a Technical Report in respect of the Revised Mineral Resources estimate as soon as it is available, and in any event within the regulated 45-day period after this news release. The Revised Mineral Resources estimate will now be incorporated into a re-optimized open pit mine plan for the Project, which will include a re-evaluation of Mineral Reserves and an economic assessment based thereon. It is anticipated this work will be completed during 2024-25 and will result in a revised PFS including a revised statement of Mineral Reserves for the Project, if warranted, and an economic assessment based thereon. Accordingly, the mineral resources and economic assessment previously disclosed by <span class="xn-person">Star Diamond</span> for the Project should no longer be relied upon.</p>
<p><b>The Project</b></p>
<p>The Project is located in central <span class="xn-location">Saskatchewan</span> some 60 kilometres east of the city of Prince Albert.&nbsp;The Project is in close proximity to established infrastructure, including paved highways and the electrical power grid, which provide significant advantages for future mine development.</p>
<p>All technical information in this press release has been prepared under the supervision of <span class="xn-person">George Read</span>, Senior Vice President Corporate Development, a registered Professional Geoscientist in the Provinces of <span class="xn-location">Saskatchewan</span> and <span class="xn-location">British Columbia</span> and <span class="xn-person">Mark Shimell</span>, Vice President Exploration, a registered Professional Geoscientist in the Provinces of <span class="xn-location">Saskatchewan</span> and <span class="xn-location">Alberta</span>, who are <span class="xn-person">Star Diamond's</span> QP's under the definition of NI 43-101.</p>
<p><b>About Star Diamond Corporation<br class="dnr"></b><span class="xn-person">Star Diamond</span> is a Canadian-based corporation engaged in the acquisition, exploration and development of mineral properties. Shares of <span class="xn-person">Star Diamond</span> trade on the Toronto Stock Exchange under the trading symbol "DIAM".&nbsp;&nbsp; <span class="xn-person">Star Diamond's</span> most significant asset is its 100% interest in the Fort à la Corne Project in central Saskatchewan.&nbsp; These kimberlites are located in close proximity to established infrastructure, including paved highways and the electrical power grid, which provide significant advantages for future mine development.</p>
<p>Website&nbsp;<u><a href="https://c212.net/c/link/?t=0&amp;l=en&amp;o=4218594-1&amp;h=4212169223&amp;u=http%3A%2F%2Fwww.stardiamondcorp.com%2F&amp;a=www.stardiamondcorp.com" rel="nofollow" target="_blank">www.stardiamondcorp.com</a></u></p>
<p><b>Stay Connected with Us:<br class="dnr"></b>X (Twitter) - <a href="https://c212.net/c/link/?t=0&amp;l=en&amp;o=4218594-1&amp;h=1228229384&amp;u=https%3A%2F%2Ftwitter.com%2FStarDiamondCorp&amp;a=https%3A%2F%2Ftwitter.com%2FStarDiamondCorp" rel="nofollow" target="_blank">https://twitter.com/StarDiamondCorp</a><br class="dnr">LinkedIn - <a href="https://c212.net/c/link/?t=0&amp;l=en&amp;o=4218594-1&amp;h=4145625321&amp;u=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fstar-diamond-corp%2F&amp;a=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fstar-diamond-corp%2F" rel="nofollow" target="_blank">https://www.linkedin.com/company/star-diamond-corp/</a><br class="dnr">Facebook - <a href="https://c212.net/c/link/?t=0&amp;l=en&amp;o=4218594-1&amp;h=2042514602&amp;u=https%3A%2F%2Fweb.facebook.com%2Fstardiamondcorp&amp;a=https%3A%2F%2Fweb.facebook.com%2Fstardiamondcorp" rel="nofollow" target="_blank">https://web.facebook.com/stardiamondcorp</a><br class="dnr">Instagram - <a href="https://c212.net/c/link/?t=0&amp;l=en&amp;o=4218594-1&amp;h=311292891&amp;u=https%3A%2F%2Fwww.instagram.com%2Fstardiamondcorp&amp;a=https%3A%2F%2Fwww.instagram.com%2Fstardiamondcorp" rel="nofollow" target="_blank">https://www.instagram.com/stardiamondcorp</a><br class="dnr">YouTube - <a href="https://c212.net/c/link/?t=0&amp;l=en&amp;o=4218594-1&amp;h=2959915797&amp;u=https%3A%2F%2Fyoutube.com%2F%40StarDiamondCorp&amp;a=https%3A%2F%2Fyoutube.com%2F%40StarDiamondCorp" rel="nofollow" target="_blank">https://youtube.com/@StarDiamondCorp</a></p>
<p><b><i>Caution Regarding Forward-looking Statements</i></b></p>
<p>This press release contains "forward-looking statements" and/or "forward-looking information" (collectively, "forward-looking statements") within the meaning of applicable securities legislation. All statements, other than statements of historical fact, are forward-looking statements. Forward-looking information is often, but not always, identified by the use of words such as "anticipate", "believe", "expect", "plan", "intend", "forecast", "target", "project", "guidance", "may", "will", "should", "could", "estimate", "predict" or similar words suggesting future outcomes or language suggesting an outlook. In particular, statements regarding <span class="xn-person">Star Diamond's</span> future operations, future exploration and development activities or other development plans constitute forward-looking statements. By their nature, statements referring to mineral reserves or mineral resources constitute forward-looking statements.</p>
<p>Forward-looking statements in this press release include, but are not limited to statements with respect to the Revised Mineral Resources Estimate; pricing information and other assumptions and parameters; improvement in the Mineral Resource estimate; statements regarding the processing and analysis of, and reporting of results from, the TC bulk samples previously collected by RTEC; the re-optimization of the Star and Orion South open pits; the potential proportion of Type IIa diamonds in the Star and Orion South kimberlites and the potential for recovery of large high quality diamonds; the publication of the Technical Report; and the aim of the Company to undertake a PFS and Feasibility Study and timelines.&nbsp;&nbsp;</p>
<p>These forward-looking statements are based on <span class="xn-person">Star Diamond's</span> current beliefs as well as assumptions made by and information currently available to <span class="xn-person">Star Diamond</span> and involve inherent risks and uncertainties, both general and specific. Risks exist that forward-looking statements will not be achieved due to a number of factors including, but not limited to, developments in world diamond markets, changes in diamond prices, risks relating to fluctuations in the Canadian dollar and other currencies relative to the US dollar, changes in exploration, development or mining plans due to exploration results and changing budget priorities of <span class="xn-person">Star Diamond</span>, the impact of changes in the laws and regulations regulating mining exploration, development, closure, judicial or regulatory judgments and legal proceedings, operational and infrastructure risks and the additional risks described in <span class="xn-person">Star Diamond's</span> most recently filed Annual Information Form, annual and interim MDA.</p>
<p>SOURCE Star Diamond Corporation</p>
<img alt="" src="https://rt.newswire.ca/rt.gif?NewsItemId=C8345&amp;Transmission_Id=202407241106CANADANWCANADAPR_C8345&amp;DateId=20240724" style="border:0px; width:1px; height:1px;"><p>For further information: <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="c3b0b7a2b1a7aaa2aeacada7a0acb1b383b0b7a2b1a7aaa2aeacada7a0acb1b3eda0acae">[email&nbsp;protected]</a> or (306) 664-2202, www.stardiamondcorp.com</p>
          
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
          
          
            
        </div>
      </div>
    </section>
<div class="modal fade" id="financial-modal" tabindex="-1" role="dialog" aria-labelledby="financial-modalLabel" aria-modal="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content" id="stock-modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
          <h3 class="modal-title" id="financial-modalLabel">Modal title</h3>
        </div>		
     </div>
   </div>
</div>
  </article>
  
  
  
	<section class="container read-more-explore">
		
			<div class="row">
				<div class="col-sm-10 col-sm-offset-1">
					
						<div class="row">
							<div class="col-sm-12">
								<h2 class="section-header">Organization Profile</h2>
							</div>
						</div>
						<div class="row">
							<!-- define truncate function -->
							<!-- USED IN: org profile bottom of release -->
							<!-- Left:  Headline + Text -->
							<!-- Right: Image -->
							
							<div class="col-sm-8 col-lg-9 pull-left card">
								<h3><a class="news-release" href="/news/star-diamond-corporation/" title="">Star Diamond Corporation</a></h3>
								
								<div>
									<ul class="list-unstyled">																				
										
											
											  
											  <p class="section-header"><strong>Also from this source</strong></p>
											  
												
													<li>
														<div>
															<p>
					  <a class="omniture-news-release-readMore-clicks" href="star-diamond-corporation-announces-leadership-team-changes-849207754.html" data-omniture="{&quot;page&quot;:&quot;Also from this source&quot;,&quot;val&quot;:&quot;1&quot;}" title="">STAR DIAMOND CORPORATION ANNOUNCES LEADERSHIP TEAM CHANGES </a>
					 </p>
														</div>
													</li>
												
													<li>
														<div>
															<p>
					  <a class="omniture-news-release-readMore-clicks" href="star-diamond-corporation-announces-board-changes-830640421.html" data-omniture="{&quot;page&quot;:&quot;Also from this source&quot;,&quot;val&quot;:&quot;2&quot;}" title="">STAR DIAMOND CORPORATION ANNOUNCES BOARD CHANGES </a>
					 </p>
														</div>
													</li>
												
													<li>
														<div>
															<p>
					  <a class="omniture-news-release-readMore-clicks" href="star-diamond-corporation-announces-third-quarter-2025-results-873267706.html" data-omniture="{&quot;page&quot;:&quot;Also from this source&quot;,&quot;val&quot;:&quot;3&quot;}" title="">STAR DIAMOND CORPORATION ANNOUNCES THIRD QUARTER 2025 RESULTS </a>
					 </p>
														</div>
													</li>
												
											
										
									</ul>
								</div>
							</div>
						</div>
					
					
				</div>
			</div>
		
	</section>

  
  
  <!--<section class="fw-bg fw-bg--gray-lightest just-read">
    <div class="container">
      <sly data-sly-use.social="./template/fragments/socialSharing.html" data-sly-call="org.apache.sling.scripting.sightly.apps.prncom.components.structure.newsreleasepage.template.fragments.socialSharing__002e__html$1@2f4b7a4d"
        data-sly-unwrap></sly>
    </div>
  </section>-->
  <input type="hidden" value="/etc.clientlibs/prncom/clientlibs/clientlibs-common/resources/js/page.template-b.js" id="jsFileName">
  <input type="hidden" value="v5vsz4c0cbh" id="publicKey">

			
			
			
		
		
	

  </main>
  
	
    	 
		
        
        
		
		
        	
				<input type="hidden" id="pageName" value="CNW | News Releases | English | STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE">
				<input type="hidden" id="prop2" value="CNW | News Releases | English | STAR - ORION SOUTH DIAMOND PROJECT REVISED MINERAL RESOURCES ESTIMATE EXHIBITS SIGNIFICANT INCREASE">
				<input type="hidden" id="prop9" value="EN">
				<input type="hidden" id="evar22" value="EN">
				<input type="hidden" id="evar77" value="www.newswire.ca">
			
				
			<input type="hidden" id="channel" value="CNW News Releases">
			<input type="hidden" id="prop6" value="CNW_News Releases">	
        	
		
		
		<input type="hidden" id="events" value="event10">
		<input type="hidden" id="prop9" value="en">
		<input type="hidden" id="prop35" value="MNG">     
		<input type="hidden" id="prop37">  
		<input type="hidden" id="prop47" value="Inline">
		
			<input type="hidden" id="prop74" value="https://www.newswire.ca/news-releases/star-orion-south-diamond-project-revised-mineral-resources-estimate-exhibits-significant-increase-858739937.html">
		
		<input type="hidden" id="prop26" value="Jul 24, 2024, 11:06 ET">
		<input type="hidden" id="evar19" value="202407241106CANADANWCANADAPR_C8345">
		<input type="hidden" id="evar17" value="4468734">
		<input type="hidden" id="evar18" value="C8345">
		<input type="hidden" id="isNewsDetails" value="true"> 
        <input type="hidden" id="companies" value="Star Diamond Corporation">
        <input type="hidden" id="accountNumber">
        <input type="hidden" id="transmissionId" value="202407241106CANADANWCANADAPR_C8345">
        <input type="hidden" id="storyId" value="4468734">
		<input type="hidden" id="evar78" value="2024-07-24">
	

  

<div>
			 
<footer id="js-footer" class="py-0">
	<div class="main-footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-3 col-xs-12 hidden-xs">
					




    
    
    <div class="footerContact">


<div class="footer-head hidden-xs ">
    <h2 class="omniture-footer-main">Contact Cision</h2>
</div>
<ul class="footer-contact">
    
        <li>
            
                <div class="pull-left">
                    <span aria-hidden="true" class="btr bt-mobile bt-lg hidden-xs"></span>
                </div>
            
            <div class="footer-num ">
                
                    <a href="tel:866-245-2317">866-245-2317</a><br>
                
                from 8 AM - 10 PM ET
            </div>
        </li>
    
    
    
    
</ul>
<style>
    .footer-contact li {
    padding-bottom:10px;
    display:flex;
    align-items: center;
    }
</style></div>


    
    
    <div class="footerDropdown">


    

    
        <div class="dropup global-sites  hidden-xs" data-icon-toggle="footer-contact-dropup">
            <button class="dropdown-toggle btn-style" aria-controls="dropdown-menu-contact-us" type="button" data-toggle="dropdown" aria-expanded="false">Contact Us
                <span aria-hidden="true" class="btb bt-angle-up"></span></button>
            <ul id="dropdown-menu-contact-us" class="dropdown-menu">
                
                    
                        <li>
                            <a title="Become a Client" href="/contact-us/" target="_self">Become a Client</a>
                        </li>
                    
                        <li>
                            <a title=" Request a Demo " href="/request-a-demo/" target="_self"> Request a Demo </a>
                        </li>
                    
                        <li>
                            <a title=" Editorial Bureaus " href="/contact-us/editorial-bureaus/" target="_self"> Editorial Bureaus </a>
                        </li>
                    
                        <li>
                            <a title=" Partnerships " href="/contact-us/partnerships/" target="_self"> Partnerships </a>
                        </li>
                    
                        <li>
                            <a title=" General Enquiries " href="/general-inquiries/" target="_self"> General Enquiries </a>
                        </li>
                    
                        <li>
                            <a title=" Media" href="/contact-us/media/" target="_self"> Media</a>
                        </li>
                    
                
            </ul>
        </div>
    


</div>


    
    
    <div class="footerSocial"><!-- <div data-sly-test="false" class="cq-placeholder" data-emptytext="Edit the social component"></div>
 -->
<div class="social-links hidden-xs">
   
   
       <a href="https://www.linkedin.com/company/cisioncanada/" title="LinkedIn" aria-label="LinkedIn" target="_blank"><span aria-hidden="true" class="fab fab-linkedin-alt"></span></a>
   
  </div></div>



					<div class="hidden-xs">
						
					</div>
				</div>
				<div class="col-sm-3 col-xs-12 hidden-xs">
					




    
    
    <div class="footerList">
	
        <div class="footer-head">
		
		
        <h2 class="omniture-footer-main hidden-xs">Products</h2>
		
        </div>
    

    
     
		<ul class="list-unstyled">
        
            
                <li>
                <a class="omniture-footer_subsites" title="Cision Communications Cloud®" href="https://www.newswire.ca/products/communications-cloud" target="_blank">Cision Communications Cloud®</a>
                </li>
                
            
                <li>
                <a class="omniture-footer_subsites" title="Media Monitoring" href="https://www.cision.ca/monitoring-analytics/online/" target="_blank">Media Monitoring</a>
                </li>
                
            
                
                <li>
                    <a class="omniture-footer-main" title="Content Distribution" href="https://www.newswire.ca/products/content-distribution" target="_self">Content Distribution</a>   
                </li>
            
                
                <li>
                    <a class="omniture-footer-main" title="Multimedia Distribution" href="https://www.newswire.ca/products/multimedia-distribution-options" target="_self">Multimedia Distribution</a>   
                </li>
            
                
                <li>
                    <a class="omniture-footer-main" title="Measurement &amp; Analytics" href="https://www.newswire.ca/products/Media-Measurement--Analytics" target="_self">Measurement &amp; Analytics</a>   
                </li>
            
                
                <li>
                    <a class="omniture-footer-main" title="Investor Relations" href="https://www.newswire.ca/products/investor-relations" target="_self">Investor Relations</a>   
                </li>
            
        
		</ul></div>



					<div class="hidden-xs">
						
					</div>
				</div>
				<div class="col-sm-3 col-xs-12 hidden-xs">
					




    
    
    <div class="footerList">
	
        <div class="footer-head">
		
        <h2 class="omniture-footer_subsites hidden-xs">About</h2>
		
		
        </div>
    

    
     
		<ul class="list-unstyled">
        
            
                <li>
                <a class="omniture-footer_subsites" title="About Cision Canada" href="http://cnw.en.mediaroom.com/aboutus/" target="_blank">About Cision Canada</a>
                </li>
                
            
                <li>
                <a class="omniture-footer_subsites" title="About Cision" href="http://www.cision.ca/" target="_blank">About Cision</a>
                </li>
                
            
                <li>
                <a class="omniture-footer_subsites" title="Media Partners" href="https://www.newswire.ca/contact-us/media-partners.html" target="_blank">Media Partners</a>
                </li>
                
            
                
                <li>
                    <a class="omniture-footer-main" title="Careers" href="https://www.cision.ca/careers/" target="_self">Careers</a>   
                </li>
            
                
                <li>
                    <a class="omniture-footer-main" title="Accessibility Statement" href="/contact-us/general-enquiries/" target="_self">Accessibility Statement</a>   
                </li>
            
        
		</ul></div>


    
    
    <div class="footerDropdown">


    

    
        <div class="dropup global-sites  hidden-xs" data-icon-toggle="footer-contact-dropup">
            <button class="dropdown-toggle btn-style" aria-controls="dropdown-menu-global-sites" type="button" data-toggle="dropdown" aria-expanded="false">Global Sites
                <span aria-hidden="true" class="btb bt-angle-up"></span></button>
            <ul id="dropdown-menu-global-sites" class="dropdown-menu">
                
                    
                        <li>
                            <a title="APAC" href="https://www.prnewswire.com/apac/" target="_self">APAC</a>
                        </li>
                    
                        <li>
                            <a title="APAC - Simplified Chinese" href="https://www.prnasia.com/" target="_blank">APAC - Simplified Chinese</a>
                        </li>
                    
                        <li>
                            <a title="APAC - Traditional Chinese" href="https://www.prnewswire.com/apac/zh/" target="_self">APAC - Traditional Chinese</a>
                        </li>
                    
                        <li>
                            <a title="Brazil" href="https://prnewswire.com.br/" target="_blank">Brazil</a>
                        </li>
                    
                        <li>
                            <a title="Canada" href="https://www.newswire.ca/en/" target="_blank">Canada</a>
                        </li>
                    
                        <li>
                            <a title="Czech" href="https://www.prnewswire.com/cs/tiskova-zprava/" target="_blank">Czech</a>
                        </li>
                    
                        <li>
                            <a title="Denmark" href="https://www.prnewswire.com/da/pressemeddelelser/" target="_blank">Denmark</a>
                        </li>
                    
                        <li>
                            <a title="Finland" href="https://www.prnewswire.com/fi/lehdistotiedotteet/" target="_blank">Finland</a>
                        </li>
                    
                        <li>
                            <a title="France" href="https://www.prnewswire.com/fr/communiques-de-presse/" target="_blank">France</a>
                        </li>
                    
                        <li>
                            <a title="Germany" href="https://www.prnewswire.com/de/pressemitteilungen/" target="_blank">Germany</a>
                        </li>
                    
                        <li>
                            <a title="India" href="https://www.prnewswire.com/in/" target="_blank">India</a>
                        </li>
                    
                        <li>
                            <a title="Indonesia" href="https://www.prnewswire.com/id/" target="_self">Indonesia</a>
                        </li>
                    
                        <li>
                            <a title="Israel" href="https://www.prnewswire.com/il/news-releases/" target="_blank">Israel</a>
                        </li>
                    
                        <li>
                            <a title="Japan" href="https://www.prnewswire.com/jp/" target="_blank">Japan</a>
                        </li>
                    
                        <li>
                            <a title="Korea" href="https://www.prnewswire.com/kr/" target="_blank">Korea</a>
                        </li>
                    
                        <li>
                            <a title="Mexico" href="https://prnewswire.com.mx/" target="_blank">Mexico</a>
                        </li>
                    
                        <li>
                            <a title="Middle East" href="https://www.prnewswire.com/ae/news-releases/" target="_blank">Middle East</a>
                        </li>
                    
                        <li>
                            <a title="Middle East - Arabic" href="https://www.prnewswire.com/ae/ar/news-releases/" target="_blank">Middle East - Arabic</a>
                        </li>
                    
                        <li>
                            <a title="Netherlands" href="https://www.prnewswire.com/nl/persberichten/" target="_blank">Netherlands</a>
                        </li>
                    
                        <li>
                            <a title="Norway" href="https://www.prnewswire.com/no/pressemeldinger/" target="_blank">Norway</a>
                        </li>
                    
                        <li>
                            <a title="Poland" href="https://www.prnewswire.com/pl/komunikat-prasowy/" target="_blank">Poland</a>
                        </li>
                    
                        <li>
                            <a title="Portugal" href="https://www.prnewswire.com/pt/comunicados-de-imprensa/" target="_blank">Portugal</a>
                        </li>
                    
                        <li>
                            <a title="Russia" href="https://www.prnewswire.com/ru/press-releases/" target="_blank">Russia</a>
                        </li>
                    
                        <li>
                            <a title="Slovakia" href="https://www.prnewswire.com/sk/tlacova-sprava/" target="_blank">Slovakia</a>
                        </li>
                    
                        <li>
                            <a title="Spain" href="https://www.prnewswire.com/es/comunicados-de-prensa/" target="_blank">Spain</a>
                        </li>
                    
                        <li>
                            <a title="Sweden" href="https://www.prnewswire.com/sv/pressmeddelanden/" target="_blank">Sweden</a>
                        </li>
                    
                        <li>
                            <a title="United States" href="https://www.prnewswire.com/" target="_blank">United States</a>
                        </li>
                    
                        <li>
                            <a title="Vietnam" href="https://www.prnewswire.com/vn/" target="_blank">Vietnam</a>
                        </li>
                    
                
            </ul>
        </div>
    


</div>



					<div class="hidden-xs">
						
					</div>
				</div>
				<div class="col-sm-3 col-xs-12 hidden-xs">
					




    
    
    <div class="footerList">
	

    
        <div class="footer-head">
         
			<h2>My Services </h2>
			
        </div>
    
     
		<ul class="list-unstyled">
        
            
                
                <li>
                    <a class="omniture-footer-main" title="All News Releases" href="/news-releases/news-releases-list/" target="_self">All News Releases</a>   
                </li>
            
                <li>
                <a class="omniture-footer_subsites" title="Platform Login&lt;br /&gt;
" href="https://app.prnewswire.com/login/auto" target="_blank">Platform Login<br>
</a>
                </li>
                
            
                <li>
                <a class="omniture-footer_subsites" title="Next Gen Communications Cloud" href="https://app2.cision.com/" target="_blank">Next Gen Communications Cloud</a>
                </li>
                
            
                <li>
                <a class="omniture-footer_subsites" title="Cision Communications Cloud®" href="https://app.cision.com/#/login?lang=en-ca" target="_blank">Cision Communications Cloud®</a>
                </li>
                
            
                
                <li>
                    <a class="omniture-footer-main" title="my CNW&lt;br /&gt;
" href="/mycnw/login/" target="_self">my CNW<br>
</a>   
                </li>
            
                <li>
                <a class="omniture-footer_subsites" title="Data Privacy" href="https://gdpr.cision.com/" target="_blank">Data Privacy</a>
                </li>
                
            
        
		</ul></div>


    
    
    <div class="customrte">


	
		<section style="background-color : " class="lead-wrapper text-center     ">
			<div style="--bordercolor: #000000 ; --borderwidth: 1.5px" class="   ">
				
				
					<div class="text-content">
					   <p style="text-align: left;">Do not sell or share my personal information:</p>
<ul style="list-style-type: disc; padding-left: 20.0px;">
<li style="text-align: left;">Submit via <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="7525071c0314160c35161c061c1a1b5b161a18">[email&nbsp;protected]</a>&nbsp;</li>
<li style="text-align: left;">Call Privacy toll-free: 877-297-8921</li>
</ul>

					</div>
				
			</div>
		</section>
	
	


</div>



					<div>
						
					</div>
				</div>
				<!-- Footer Mobile View Specific Code -->
				<div class="visible-xs col-xs-12 text-center">
					


    
    	<div class="footer-head">
        	<h2><a href="/contact-us" target="_self">Contact Cision</a></h2>
        </div>
    
    	<div class="footer-head">
        	<h2><a href="/products/overview" target="_self">Products</a></h2>
        </div>
    
    	<div class="footer-head">
        	<h2><a href="http://cnw.en.mediaroom.com/aboutus/" target="_blank">About</a></h2>
        </div>
    



				</div>
				<div class="col-xs-12 visible-xs dropup">
					


    <a href="" title="" class="dropdown-toggle icon-toggle mobile-my-services hidden-lg hidden-sm" data-toggle="dropdown" data-icon-toggle="footer-services-dropup">My Services <i class="btr bt-angle-up"></i></a>
        <ul class="dropdown-menu">
            
                
                    <li><a title="All News Releases" href="/news-releases/" target="_self">All News Releases</a>
                    </li>
                
                    <li><a title="Platform" href="https://cnwportal.prnewswire.com/Login.aspx" target="_blank">Platform</a>
                    </li>
                
                    <li><a title="Next Gen Communications Cloud" href="https://app2.cision.com/" target="_blank">Next Gen Communications Cloud</a>
                    </li>
                
                    <li><a title="Cision Communications Cloud" href="https://app.cision.com/#/login?lang=en-ca" target="_blank">Cision Communications Cloud</a>
                    </li>
                
                    <li><a title="my CNW" href="/mycnw/login/" target="_blank">my CNW</a>
                    </li>
                
            
        </ul>

            




				</div>
				<div class="visible-xs col-xs-12 text-center">
					

	<a href="tel:877-269-7890" title="Contact Us" class="call-mobile hidden-lg hidden-sm">
    	<i class="btr bt-mobile bt-lg"></i> 877-269-7890<br>
    	from 8 AM - 10 PM ET
    </a>
				</div>
				<!-- Footer Mobile View Specific Code Ends -->
			</div>
		</div>
	</div>
	<!-- Navigation Footer -->
	<div>
		
 

    <div class="sub-footer">
              <div class="container">
                <div class="row">
                  <div class="col-md-9 col-sm-9 col-lg-9 col-xs-12">
                    <ul>
                        
                          
                          	<li><a class="omniture-footer-links" href="http://cnw.en.mediaroom.com/privacy-terms-of-use" title="Terms of Use" target="_self">Terms of Use</a></li>
                          
                          	<li><a class="omniture-footer-links" href="/cision-information-security-policy/" title="Information Security Policy" target="_self">Information Security Policy</a></li>
                          
                          	<li><a class="omniture-footer-links" href="/sitemap/" title="Site Map" target="_self">Site Map</a></li>
                          
                          	<li><a class="omniture-footer-links" href="/cookies/" title="Cookie Settings" target="_self">Cookie Settings</a></li>
                          
                          	<li><a class="omniture-footer-links" href="https://www.cision.com/about/accessibility/" title="Accessibility Statement" target="_blank">Accessibility Statement</a></li>
                          
                        
                    </ul>
                  </div>
                  <div class="col-md-3 col-sm-3 col-lg-3 col-xs-12 ">
                    <span class="pull-right pull-none-xs">Copyright © 2025 CNW Group Ltd. All Rights Reserved. A Cision&nbsp;company.&nbsp;</span>
                  </div>
                </div>
              </div>
	</div>
	</div>
</footer>

</div>   


</div>


 










<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="/etc.clientlibs/prncom/clientlibs/clientlibs-common/resources/js/lib/require.js" loading="defer"></script>

<script>

    // Disabled logic option for per page dropdown

    if (document.querySelectorAll('select.filter-selector[data-totallist]').length > 0 && document.getElementById('advNewsCountID') === null) {
        var getTotalcount = Math.ceil(parseFloat(document.querySelector('select.filter-selector[data-totallist]').getAttribute('data-totallist')) / 25);

        document.querySelectorAll('select.filter-selector:not(#resourceType)').forEach(function(selectElement) {
            for (var i = getTotalcount; i < selectElement.options.length; i++) {
                selectElement.options[i].disabled = true;
            }
        });
    }
    if (document.getElementById("jsFileName")) {
        var jsFileName =  document.getElementById("jsFileName").value;
    }
    if(document.querySelectorAll('.home-page').length > 0 && !document.querySelector('.home-page').classList.contains('mycnw-credentials')){
        requirejs(['/etc.clientlibs/prncom/clientlibs/clientlibs-common/resources/js/main.js'], function (common) {
            // page specific js
            if (jsFileName) {
                requirejs([jsFileName]);
            }
        });
    }else if(document.querySelectorAll('.prncom_news-releases_headline-listing').length > 0){

         requirejs(['/etc.clientlibs/prncom/clientlibs/clientlibs-common/resources/js/newrelease.js'], function (common) {
            // page specific js
            if (jsFileName) {
                requirejs([jsFileName]);
            }
        });

    }else if(document.querySelectorAll('.inline-gallery-template').length > 0 && document.querySelectorAll('.static-gallery-template').length > 0){

         requirejs(['/etc.clientlibs/prncom/clientlibs/clientlibs-common/resources/js/template.js'], function (common) {
            // page specific js
            if (jsFileName) {
                requirejs([jsFileName]);
            }
        });

    }else{
        requirejs(['/etc.clientlibs/prncom/clientlibs/clientlibs-common/resources/js/common.js'], function (common) {
            // page specific js
            if (jsFileName) {
                requirejs([jsFileName]);
            }
        });
    }
</script>

<!--<sly data-sly-test="false ">-->

    
<script src="/etc.clientlibs/clientlibs/granite/jquery.min.js"></script>
<script src="/etc.clientlibs/clientlibs/granite/utils.min.js"></script>
<script src="/etc.clientlibs/cision-revamp/clientlibs/clientlib-showhide.min.js"></script>
<script src="/etc.clientlibs/clientlibs/granite/jquery/granite.min.js"></script>
<script src="/etc.clientlibs/prncom/components/content/imageCarousel/clientlib.min.js"></script>



<!--</sly>-->
<script src="/etc.clientlibs/prncom/clientlibs/clientlibs-common/resources/js/ticker_model.js"></script>

    
<script src="/etc.clientlibs/prncom/clientlibs/component-clientlibs.min.js"></script>




    
<script src="/etc.clientlibs/prncom/components/global/menu/clientlibs.min.js"></script>





    <script type="module" src="https://cdn.jsdelivr.net/npm/media-chrome/all/+esm"></script>



</body></html>"""

In [51]:
import pandas as pd

tonnage_keywords = {
    "tonnage",
    "tonnes",
    "tons",
    "ton",
    "tonn",
}

grade_keywords = {"grade", "avg", "average"}

contained_keywords = {"contained", "cont", "metal", "content"}

measured_keywords = {
    "measured",
    "meas",
    "m",
}

indicated_keywords = {
    "indicated",
    "ind",
    "i",
}

inferred_keywords = {
    "inferred",
    "inf",
    "infe",
}

meas_ind_keywords = {
    "meas_ind",
    "meas-ind",
    "meas ind",
    "meas/ind",
    "meas / ind",
    "meas&ind",
    "meas & ind",
    "m+i",
    "m + i",
    "mi",
    "m/i",
    "m / i",
    "m&i",
    "m & i",
}

probable_keywords = {
    "probable",
    "prob",
    "proba",
    "pro",
    "p",
}

proven_keywords = {
    "proven",
    "prov",
    "pro",
    "p",
}

prov_prob_keywords = {
    "prov_prob",
    "prov-prob",
    "prov prob",
    "prov/prob",
    "prov / prob",
    "proven + probable",
    "proven & probable",
    "proven/probable",
    "proven / probable",
    "p + p",
    "p & p",
    "p/p",
    "p / p",
}

keyword_set1 = list(tonnage_keywords | grade_keywords | contained_keywords)
keyword_set2 = list(
    measured_keywords
    | indicated_keywords
    | inferred_keywords
    | meas_ind_keywords
    | probable_keywords
    | proven_keywords
    | prov_prob_keywords
)


def is_keyword_in_text(keywords: list, text: str) -> bool:
    for keyword in keywords:
        if keyword in text:
            return True
    return False

print(keyword_set1)
print(keyword_set2)

# TODO: optimize with dynamic programming and regex
def is_resource_table(df: pd.DataFrame) -> bool:
    rows = df.index
    cols = df.columns
    for i in range(len(rows)):
        for j in range(len(cols)):
            current_cell = str(df.iat[i, j])
            if sum(c.isdigit() for c in current_cell) < len(current_cell) / 2:
                continue
            set1 = False
            set2 = False
            for ii in range(len(rows)):
                ahead_cell = str(df.iat[ii, j]).lower()
                if not set1:
                    set1 = is_keyword_in_text(keyword_set1, ahead_cell)
                if not set2:
                    set2 = is_keyword_in_text(keyword_set2, ahead_cell)
                if set1 and set2:
                    return True
            for jj in range(len(cols)):
                ahead_cell = str(df.iat[i, jj]).lower()
                if not set1:
                    set1 = is_keyword_in_text(keyword_set1, ahead_cell)
                if not set2:
                    set2 = is_keyword_in_text(keyword_set2, ahead_cell)
                if set1 and set2:
                    return True
    return False

['cont', 'contained', 'tons', 'avg', 'metal', 'grade', 'tonnage', 'content', 'ton', 'tonn', 'tonnes', 'average']
['prov_prob', 'ind', 'mi', 'meas ind', 'p / p', 'infe', 'meas-ind', 'inf', 'm / i', 'prov', 'proven', 'measured', 'meas&ind', 'prov prob', 'indicated', 'p + p', 'm&i', 'prov / prob', 'm + i', 'p', 'meas_ind', 'proven / probable', 'meas / ind', 'p & p', 'probable', 'inferred', 'pro', 'm', 'i', 'm+i', 'meas/ind', 'meas', 'p/p', 'm & i', 'm/i', 'prov-prob', 'proven + probable', 'proba', 'meas & ind', 'prov/prob', 'proven & probable', 'prob', 'proven/probable']